### ISSUE TITLE
Tracker Team Orientation to Github

### ISSUE THREAD

**Issue by dlounsbu** [dlounsbu/NYHEALing-IPAtracker-support#1]
# For every service request, create a New issue. Click on the Service Request Issue template to quickly set up your New issue. Be sure to:

- [ ] ASSIGN the New issue to the IPA Tracker Service Requests PROJECT. The card will be triaged to the 'TO DO' column.
- [ ] ADD Labels to indicate county and other descriptive information.

**Comment by dlounsbu** [comment]
@ambuch Please consider editing your github profile with a face pic, as @mirmahdi and I have.

**Comment by ambuch** [comment]
Done!
