### ISSUE TITLE
Service Request by Donrie on bug in Specification when entering Resources  

### ISSUE THREAD

**Issue by donriepurcell** [dlounsbu/NYHEALing-IPAtracker-support#13]
- [ ] Qualtrics Service Request Form was received from User
- [ ] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [x] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by dlounsbu** [comment]
From: Donrie Purcell 
Sent: Wednesday, August 18, 2021 8:26 PM
To: Jeff Bazinet <jbazinet@northcountryinitiative.org>
Cc: david lounsbury <david.lounsbury@einsteinmed.org>; Nicholas Bove <nicholas.bove@einsteinmed.org>; Anika Buch <ambuch@princeton.edu>
Subject: Bug: Tracker crashes when entering data into Resources 

Hi Jeff, 

I was trying to finish up entering the data for Erie County and suddenly the system crashes when entering data into Resources in Specification.
I don’t understand why as the system worked perfectly all day.
Whatever you can do to help I would greatly appreciate it.


Regards
Donrie Purcell, PhD, MPH

Every generation has the obligation to free men's minds for a look at new worlds,....to look out from a higher plateau than the last generation.
Ellison S. Onizuka 


CONFIDENTIALITY: This email (including any attachments) may contain confidential, proprietary and/or privileged information. Any duplication, copying, distribution, dissemination, transmission, disclosure or use in any manner of this email (including any attachments) without the authorization of the sender is strictly prohibited. If you receive this email (including any attachments) in error, please notify the sender and delete this email (including any attachments) from your system. Thank you.
![Screen Shot 2021-08-18 at 8 16 06 PM](https://user-images.githubusercontent.com/20574023/129991076-77fb12ba-1ba8-4d7a-bf71-2deaae5e25f9.png)
![Screen Shot 2021-08-18 at 8 16 19 PM](https://user-images.githubusercontent.com/20574023/129991077-248a2a5f-884f-4563-8c5a-7a419191ebe3.png)

**Comment by donriepurcell** [comment]
From: Donrie Purcell <donrie.purcell@einsteinmed.org>
Date: Thursday, August 19, 2021 at 1:38 PM
To: Emma Rodgers <emr2241@columbia.edu>, Samantha W. Lang <sl4732@columbia.edu>, Sydney Bell <sb4424@columbia.edu>, Phoebe M. Kelleher <pmk2136@columbia.edu>, Anna N. Weiskopf <aw3391@columbia.edu>, Mia-Cara Christopher <mm5651@columbia.edu>, Erin Kim <ek3183@columbia.edu>
Cc: Jessica Neufeld <jn2434@columbia.edu>, david lounsbury <david.lounsbury@einsteinmed.org>, Nicholas Bove <nicholas.bove@einsteinmed.org>
Subject: Re: Bug in the system
Hi all,

I just checked the IPA Tracker and the vendor has corrected the bug in the system. 

Thank for your patience.

Regards
Donrie Purcell, PhD, MPH

Every generation has the obligation to free men's minds for a look at new worlds,....to look out from a higher plateau than the last generation.
Ellison S. Onizuka 


CONFIDENTIALITY: This email (including any attachments) may contain confidential, proprietary and/or privileged information. Any duplication, copying, distribution, dissemination, transmission, disclosure or use in any manner of this email (including any attachments) without the authorization of the sender is strictly prohibited. If you receive this email (including any attachments) in error, please notify the sender and delete this email (including any attachments) from your system. Thank you.

**Comment by dlounsbu** [comment]
Excellent. Do you want to close this issue?
