### ISSUE TITLE
Service Request by Nick Bove - System crashes when deleting Measures with type 'Other'

### ISSUE THREAD

**Issue by NBOVE1** [dlounsbu/NYHEALing-IPAtracker-support#17]
- [ ] Qualtrics Service Request Form was received from User
- [ ] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by NBOVE1** [comment]
System is crashing when attempting to delete measures:

![image](https://user-images.githubusercontent.com/88558561/131378582-57f1695f-4ed7-4a6b-9743-c92b8602d3fb.png)

![image](https://user-images.githubusercontent.com/88558561/131378676-eea263f6-ce67-4493-81ae-a24d6e6c2dc0.png)

**Comment by dlounsbu** [comment]
Hi Nick:

Is this problem associated with a specific county? 

Is this for Measures that are type "Other" only, by chance? 

DL

**Comment by NBOVE1** [comment]
Hi David,
Yes, this is specific to Columbia County now, though I haven't attempted to delete measures in other counties. The measures that are experiencing the issue are all type "other" measures.
Best,
Nick

**Comment by donriepurcell** [comment]
Hi Nick,
Thanks, Hopefully jeff sees it and addresses it.

**Comment by jbazinet1111** [comment]
This should be resolved but I didn't do any deletes to finish verifying the fix. Didn't want to mess with the IPA measures

**Comment by NBOVE1** [comment]
Thanks Jeff! It's now working properly.
Best,
Nick
