### ISSUE TITLE
Service Request by Nick Bove - Extend 'time out' and/or add 'time out' warning

### ISSUE THREAD

**Issue by NBOVE1** [dlounsbu/NYHEALing-IPAtracker-support#18]
- [ ] Qualtrics Service Request Form was received from User
- [ ] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by NBOVE1** [comment]
Columbia County Program Manager Lori Torgersons request is as follows: "Can the session timeout feature be eliminated or lengthened?  I surmised what I think happened with the updates I had made to the COPE IPA that didn't save yesterday - I think that while I hit the small save button numerous times, I didn't hit the Save All button until what would have been the end of my session, but when I did so - I think it had already timed out."

**Comment by dlounsbu** [comment]
@jbazinet1111 

I think we can add time out time, or is there utility to timing out sooner than later?

If it is possible to give a Time Out Warning, we can do that, too. 

Logins back in has never been an issue for me, as it remembers me. 

Thoughts?!

**Comment by dlounsbu** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in'>


<p class=MsoNormal><b><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
mso-fareast-font-family:"Times New Roman"'>From:</span></b><span
style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
"Times New Roman"'> Jeff Bazinet [mailto:jbazinet@northcountryinitiative.org] <br>
<b>Sent:</b> Friday, September 3, 2021 2:16 PM<br>
<b>To:</b> Anika Buch &lt;ambuch@princeton.edu&gt;; Donrie Purcell
&lt;donrie.purcell@einsteinmed.org&gt;; Nicholas Bove
&lt;nicholas.bove@einsteinmed.org&gt;; david lounsbury
&lt;david.lounsbury@einsteinmed.org&gt;<br>
<b>Subject:</b> RE: IPA Tracker Bugs<o:p></o:p></span></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>



CAUTION: This   email comes from an external source; the attachments and/or links may   compromise our secure environment. Do not open or click on suspicious emails.   Please click on the “Phish Alert” button on the top right of the Outlook   dashboard to report any suspicious emails.
--




<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
color:#1F497D'>Regarding the timeout issue….I sent this a while back. I can
reset the timeout but need to know what value you’re looking for?<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
color:#1F497D'><o:p>&nbsp;</o:p></span></p>


</body>

</html>

**Comment by dlounsbu** [comment]
> Regarding the timeout issue….I sent this a while back. I can reset the timeout but need to know what value you’re looking for?

Hi @jbazinet1111 

What is it now? Maybe 5-10 min? 

Make it 20 minutes. 

Question, when it times out, is all data autosaved? 

And, what do you think about adding a Time Out warning? 

DL

**Comment by mirmahdi** [comment]
Hi All,

For the timeout issue, when you want to show a warning that the session is
timing out, you can also give the user the freedom of extending the session
clock. This is what happens in many internet banking web apps today on
almost all major banks. This makes is convenient for the users if they are
entering some data and need more time to finish, without having to save
their work and log back in. Just a thought though!

**Comment by jbazinet1111** [comment]
This is set to 20 minutes.
There is no warning message as that requires a different framework for the entire application (not done from the very beginning so as to support multiple browsers).

**Comment by dlounsbu** [comment]
Hi Jeff: 

This is very good information. 

Nick and Donrie, let's just increase user awareness about the 20minute time out. And let's report that we considered adding a warning, but that it was not advised, due to concerns about browser compatibility. 

For me, if I get timed out, I can easily get back it - my browser, Chrome, keeps my user ID and password in the portal form. So, no re-typing for me. 

Jeff, what is the best recommended browser for the Tracker? If there is a best choice browser, we should let users know. 

THANKS, David
