### ISSUE TITLE
Service Request by Donrie Purcell for Jessica to add Downloads specific to Strategies, Measures, Partners, etc.

### ISSUE THREAD

**Issue by donriepurcell** [dlounsbu/NYHEALing-IPAtracker-support#19]
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by donriepurcell** [comment]
Hi Jeff,

Please can you code the downloads in such a way that If so requested one can download only Strategies (if that's their only interest) without lumping measures or partners therein.

The same will be applicable if someone only wanted only look at downloads for Measures without an interest in Partners, Venues, etc.

Essentially, the Research team are asking for the capability to download specific aspects of the Smart Strategies without lumping them altogether, albeit we are looking at a relational database.

Kind Regards 
Donrie

**Comment by dlounsbu** [comment]
To add to Donrie's comments, the request is to add STRATEGIES to the list of components that can be downloaded individually (or in some combination with other components (e.g., Measures, Partners, Venues).

**Comment by jbazinet1111** [comment]
That's because I added it! It wasn't there beforehand.


________________________________

**Comment by donriepurcell** [comment]
I am writing Jessica an email to let her know the capacity is there now
