### ISSUE TITLE
Service Request by Nick Bove - Site is down

### ISSUE THREAD

**Issue by NBOVE1** [dlounsbu/NYHEALing-IPAtracker-support#20]
- [ ] Qualtrics Service Request Form was received from User
- [ ] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by NBOVE1** [comment]
IPA Tracker is currently down. Will the tracker be live by 10AM? I have a meeting with Columbia County to provide support around mechanics of the tracker:

![image](https://user-images.githubusercontent.com/88558561/131677520-60b4b427-addf-426d-a710-3e4babaa58a7.png)

**Comment by jbazinet1111** [comment]
Ok. Sorry. Let me take a look
________________________________

**Comment by NBOVE1** [comment]
No problem! Thank you.
