### ISSUE TITLE
Service Request by Mia  Christopher - Assistance in deleting a specific strategy

### ISSUE THREAD

**Issue by dlounsbu** [dlounsbu/NYHEALing-IPAtracker-support#21]
- [ ] Qualtrics Service Request Form was received from User
- [ ] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.
From: David Lounsbury [mailto:noreply@qemailserver.com] 
Sent: Wednesday, September 1, 2021 1:37 PM
To: david lounsbury <david.lounsbury@einsteinmed.org>
Subject: IPA Tracker Support Request Form Submitted

IPA SERVICE REQUEST SUMMARY

1. CONTACT INFORMATION:

Mia  Christopher

Email:  mm5651@columbia.edu

Phone:  2078121440

2. COUNTY

Erie

3. WHICH FEATURE(S):

SPECIFICATION: Creating, updating, deleting information to define or describe a SMART Strategy

4. BRIEF PROBLEM DESCRIPTION:

Please delete strategy 2A3

5. URGENCY:

50

6. ANYTHING ELSE TO SHARE: 

N/A

**Comment by NBOVE1** [comment]
This strategy has been deleted. I'll follow up with Mia and let her know.
Best,
Nick

**Comment by dlounsbu** [comment]
Thanks very much Nick.

DL
