### ISSUE TITLE
Service Request by Nick Bove - User log in issue

### ISSUE THREAD

**Issue by NBOVE1** [dlounsbu/NYHEALing-IPAtracker-support#22]
- [x] Problem FULLY RESOLVED and Issue is Closed
- [ ] Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by NBOVE1** [comment]
Program Manager Putnam County Login Issue: "For some reason when I enter the username/password and click login, the boxes turn yellow (login info remains) and nothing happens. I tried refreshing the page, etc. and still not working. I’m not sure what to think."

**Comment by dlounsbu** [comment]
@NBOVE1 

I suggest deleting this individual's user name via "Users". I would delete them from the list, then save and exit the Tracker. Then log back in and add the individual. 

Then log out and back in, this time testing the username and new password.

If all is good, ask them to do the same. 

If you have a problem, add Jeff to this issue and comment to him about the problem. 

THANKS

**Comment by NBOVE1** [comment]
Thank you David. This has appeared to work. I've requested that Kristin try it on her end:

![image](https://user-images.githubusercontent.com/88558561/131914665-e04b892e-4489-4ed0-a0c1-54297eb54508.png)

**Comment by dlounsbu** [comment]
@NBOVE1  If Program Manager Putnam County can log in without difficulty now, then we can close this issue.

**Comment by NBOVE1** [comment]
@dlounsbu Sure, I'll close this out as soon as the PM confirms that she can access the tracker.
