### ISSUE TITLE
Service Request by Monica Salvage 

### ISSUE THREAD

**Issue by donriepurcell** [dlounsbu/NYHEALing-IPAtracker-support#24]
- [x] Qualtrics Service Request Form was received from User
- [x] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [x] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by donriepurcell** [comment]
IPA SERVICE REQUEST SUMMARY


1. CONTACT INFORMATION:

Monika  Salvage

Email:  msalvage@cayugacounty.us

Phone:  3152531522


2. COUNTY

Cayuga


3. WHICH FEATURE(S):

MONITORING: Creating, updated or deleting information about an implemented SMART Strategy


4. BRIEF PROBLEM DESCRIPTION:

B1 - Resource monitoring: I filled in the status and $ invoiced and hit Save, but the entries don't show up in the History section below. Before I enter info in the other strategies, I'd like to make sure that this section works. Thanks.


5. URGENCY:

75


6. ANYTHING ELSE TO SHARE:

**Comment by donriepurcell** [comment]
From: donriepurcell <donrie.purcell@einsteinmed.org>
Subject: Fwd: IPA Tracker Support Request Form Submitted
Date: September 3, 2021 at 3:27:46 PM EDT
To: msalvage@cayugacounty.us
Cc: david lounsbury <david.lounsbury@einsteinmed.org>

Hi Monika,

I hope this email finds you well. Dr. Lounsbury and I worked on your request and it appears that the IPA tracker works fine in terms of what you’re trying to accomplish.

I have attached a screen shot for your review of a test that we ran together.

If it is that we somehow misconstrued what your request is, do please let us know.

We will also like to be able to assist you if you will like and I am always available for a zoom or phone call to help you.


Kind Regards 
Donrie J.R. Purcell, PhD, MPH

Every generation has the obligation to free men's minds for a look at new worlds,....to look out from a higher plateau than the last generation.
Ellison S. Onizuka  


CONFIDENTIALITY: This email (including any attachments) may contain confidential, proprietary and/or privileged information. Any duplication, copying, distribution, dissemination, transmission, disclosure or use in any manner of this email (including any attachments) without the authorization of the sender is strictly prohibited. If you receive this email (including any attachments) in error, please notify the sender and delete this email (including any attachments) from your system. Thank you.

Begin forwarded message:

**Comment by donriepurcell** [comment]
Hi Jeff 
while we were  able to help Monika, it appears that in Resources Monitoring if the user does not add a comment. The user entry is not saved for review/in the history table. 
Please can you investigate this thanks.

**Comment by dlounsbu** [comment]
Just to clarify, Jeff, if the user does not add a comment in the comment field, even with the other fields completed, it does not show up in the history table. But if the user adds and sort of comment, even their initials, then the records saves properly and shows up in the history table. This seems to be a bug just for Resources Monitoring, not other Monitoring components. Thanks and hope you have a relaxing holiday weekend.

**Comment by dlounsbu** [comment]
@jbazinet1111 Please check this. The issue is that the Monitoring record does not save to history of a comment is not typed. Or should we require a comment?

**Comment by jbazinet1111** [comment]
A comment was required for it to be saved but I have removed that requirement in the code. Let me know if you would prefer to have it back.
