### ISSUE TITLE
Service Request by David Lounsbury for Donrie - Review and update units labels for consistency

### ISSUE THREAD

**Issue by dlounsbu** [dlounsbu/NYHEALing-IPAtracker-support#25]
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by dlounsbu** [comment]
![image](https://user-images.githubusercontent.com/20574023/132063417-29100a7a-a97a-4219-abf1-294d5e116886.png)

**Comment by dlounsbu** [comment]
@donriepurcell 

Please go into Tracker Options and scroll through all PRIMARY, SECONDARY, STRUCTURAL, and OTHER MEASURES labels to make sure that all MEASURES have units labels and that the units labels are consistent. Note: use 'Persons' not 'Individuals.' Use 'Kits' not 'Units' etc., etc. 

THANKS

**Comment by donriepurcell** [comment]
Hi Profe'

I reviewed all 4 Measures in Options Categories and I changed only two option values.

1.  Secondary Measures: Safer Prescribing and Dispensing= 1.0 Number of opioid overdose deaths (from individuals to Deaths)
2.  Secondary Measures: Expand MOUD Availablilty = 2.7.1 # of individuals receiving buprenorphine/Naloxone retained beyond 6 months (from individuals to persons in agreement with all the rest)

![image](https://user-images.githubusercontent.com/80912517/132099961-0d95511d-377d-4b87-8776-e4e32cd19848.png)
![image](https://user-images.githubusercontent.com/80912517/132099988-c923f183-5ceb-4368-a9a7-136aeaad9ad7.png)

**Comment by donriepurcell** [comment]
Hi Profe'
There is one item that caught my attention with the unit of measurement as **settings**. I did not get it and will defer to your advise on it. 
![Screen Shot 2021-09-04 at 11 40 54 AM](https://user-images.githubusercontent.com/80912517/132100174-4fe960d4-f797-4f50-aad0-92e4cc324a36.png)

**Comment by dlounsbu** [comment]
Hi Donrie: 

Settings makes sense for a STRUCTURAL measure. But I wonder if we should use the term 'Venues'? 

Maybe a Setting is with a 'Venue', in this case. 

Let me know if I am making sense. 

Thanks!

**Comment by donriepurcell** [comment]
Hi Profe:
I quite agree that **Venue** may be more appropriate as a unit of measurement.

**Comment by dlounsbu** [comment]
Hi Donrie:

I want to meet with to work through these 'units' issues. 

One think to check, first off, is that the Tracker will not let regular (non-Admin) users create 'Other' measures on their own. We want users to ask us to create them, so that we can set up the units, properly, for all users. 

Best and thanks,
David

**Comment by donriepurcell** [comment]
Hi Jeff,
Please can you assist us with a feature in the **Measures Download** that will allow us to see the units of measurements currently associated with each measure. In other words,  # of individuals initiated onto interim methadone will have a unit of measurement be **persons**.
Jeff, we really need to see these in the download because it will allow us to know where there are missing units of measurements especially in the case of **other measures**  and consequently allow us to stay on top of data

**Comment by dlounsbu** [comment]
> Hi Jeff, Please can you assist us with a feature in the **Measures Download** that will allow us to see the units of measurements currently associated with each measure. In other words, **# of individuals initiated onto interim methadone** will have a unit of measurement be **persons**. Jeff, we really need to see these in the download because it will allow us to know where there are missing units of measurements especially in the case of **other measures** and consequently allow us to stay on top of data

@jbazinet1111 To add to Donrie's request, what we need in analogous to what you created for generating a download of all users, users' affiliation, and Admin vs county access. 

The download table should include  EBP Category, Primary, Sec, Structure, Other, Measure name, and units. 

How many professional hours to do this?

DL

**Comment by jbazinet1111** [comment]
Might I suggest that we have a download button on the list options page? It would download all the option data, including the measures and their units. If that works for you, I would estimate a 4 hour ordeal with deployment by Tuesday morning.

**Comment by jbazinet1111** [comment]
Did you want to proceed? I'm afraid the window is closing soon for a Tuesday delivery, but if its not needed right away, then that probably doesn't matter. Let me know.

**Comment by dlounsbu** [comment]
> Did you want to proceed? I'm afraid the window is closing soon for a Tuesday delivery, but if its not needed right away, then that probably doesn't matter. Let me know.

Dear @jbazinet1111 

Yes, this is great. Please proceed. Sorry about my delayed reply! Friday was so busy for me. 

Best,
David

**Comment by jbazinet1111** [comment]
This has been deployed a day earlier than expected. There is a download list options button available to you.

**Comment by dlounsbu** [comment]
Jeff: Excellent and thank you!
