### ISSUE TITLE
Service Request by Jessica on how best to capture IPA Implementation Status 

### ISSUE THREAD

**Issue by donriepurcell** [dlounsbu/NYHEALing-IPAtracker-support#28]
- [x] Qualtrics Service Request Form was received from User
- [x] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [x] Problem FULLY RESOLVED and Issue is Closed
- [x]  Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by donriepurcell** [comment]
<blockquote type="cite" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; font-family: &quot;Times New Roman&quot;; font-size: 18px;"><div style="margin: 0px;"><span style="font-family: -webkit-system-font, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; color: rgb(0, 0, 0);"><b>From:<span class="Apple-converted-space"> </span></b></span><span style="font-family: -webkit-system-font, &quot;Helvetica Neue&quot;, Helvetica, sans-serif;">Jessica Neufeld &lt;jn2434@columbia.edu&gt;<br></span></div><div style="margin: 0px;"><span style="font-family: -webkit-system-font, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; color: rgb(0, 0, 0);"><b>Subject:<span class="Apple-converted-space"> </span></b></span><span style="font-family: -webkit-system-font, &quot;Helvetica Neue&quot;, Helvetica, sans-serif;"><b>IPA Tracker Qs</b><br></span></div><div style="margin: 0px;"><span style="font-family: -webkit-system-font, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; color: rgb(0, 0, 0);"><b>Date:<span class="Apple-converted-space"> </span></b></span><span style="font-family: -webkit-system-font, &quot;Helvetica Neue&quot;, Helvetica, sans-serif;">September 7, 2021 at 4:07:34 PM EDT<br></span></div><div style="margin: 0px;"><span style="font-family: -webkit-system-font, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; color: rgb(0, 0, 0);"><b>To:<span class="Apple-converted-space"> </span></b></span><span style="font-family: -webkit-system-font, &quot;Helvetica Neue&quot;, Helvetica, sans-serif;">Donrie Purcell &lt;donrie.purcell@einsteinmed.org&gt;<br></span></div><br><div><div class="">

CAUTION: This email comes from an external source; the attachments and/or links may compromise our secure environment. Do not open or click on suspicious emails. Please click on the “Phish Alert” button on the top right of the Outlook dashboard to report any suspicious emails.
--


<div class=""><div dir="ltr" class="">Hi Donrie, <div class=""><br class=""><div class="">I hope you had a great long weekend. </div><div class=""><br class=""></div><div class="">I'm trying to pull a count of all the IPAs. So far, I have a count of 109 unique IPA strategies (from the strategy report and minus 3 discontinued strategies). </div><div class="">Then from there, I wanted to get an overview of the number of sectors. From a measure's report, I got a total of 164 sectors, a combination of priority sectors 1-3. </div><div class=""><br class=""></div><div class="">Is there a way to pull the implementation status of the IPAs? I'm not sure I see this as an option in the tracker but I might be looking in the wrong place. I was looking under Milestones in the IPA Monitoring section. </div><div class=""><br class=""></div><div class="">Best,</div><div class="">Jessica  </div><div class=""><div class=""><br class=""></div>--<span class="Apple-converted-space"> </span><br class=""><div dir="ltr" class="gmail_signature" data-smartmail="gmail_signature"><div dir="ltr" class=""><font class=""><br class=""></font><div dir="ltr" class=""><div dir="ltr" class=""><div dir="ltr" class=""><div dir="ltr" class=""><b class=""><font face="arial, sans-serif" class="">Jessica Neufeld, MPH</font></b></div><div class=""><font face="arial, sans-serif" class="">Program Manager </font></div><div dir="ltr" class=""><div class=""><font face="arial, sans-serif" class="">HEALing Communities Study<br class=""></font></div><div dir="ltr" class=""><font face="arial, sans-serif" class="">Social Intervention Group<br class=""></font></div><div dir="ltr" class=""></div><div class=""><font face="arial, sans-serif" class=""><span class="" style="font-stretch: normal; line-height: 19.99px; background-color: transparent;">Columbia University School of Social Work</span><br class="" style="font-stretch: normal; line-height: 19.99px; overflow: visible; background-color: transparent;"><span class="" style="font-stretch: normal; line-height: 19.99px; background-color: transparent;">1255 Amsterdam Avenue</span></font></div><div class=""><font face="arial, sans-serif" class=""><font class="">New York, NY 10027</font></font></div><div class=""><a href="mailto:jn2434@columbia.edu" target="_blank" class="">jn2434@columbia.edu</a>  </div><div class=""><span class="" style="color: rgb(34, 34, 34); font-family: arial, sans-serif;">Website: </span><span class="" style="font-family: arial, sans-serif;"> </span><a href="https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsig.columbia.edu%2F&amp;data=04%7C01%7Cdonrie.purcell%40einsteinmed.org%7C65216af7722742a9aff908d9723b2ab4%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637666420720331897%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=qmiFcN4gGgCyxGI%2Fzu5Ye4huHHWI5QRCGx%2B3xxd8J80%3D&amp;reserved=0" originalsrc="https://sig.columbia.edu/" shash="gOwlO5UbqEycu0asCMG+glsqNG2ZlsuWqcThdu4Od0w0s9mtqRib5fRIzerUPN39xUCMGpVAT30BZ1W4o/gP2n7nD//CPMbXKIgdZvTfOloGVNNT+u4vd5u16NMK0HXYI3ZrIEXEAdPu6NDSC+45g+F5rTBLm5vPIfMlTWIRN/s=" target="_blank" class="" style="font-family: arial, sans-serif; color: rgb(17, 85, 204);">https://sig.columbia.edu/</a></div><div class=""></div><div class=""><br class=""></div><div class=""><span class="" style="color: rgb(34, 34, 34); font-family: arial, sans-serif;">   </span></div></div></div></div></div></div></div></div></div></div></div></div></div></blockquote>

**Comment by donriepurcell** [comment]
From: Donrie Purcell <donrie.purcell@einsteinmed.org>
Subject: Re: IPA Tracker Qs
Date: September 7, 2021 at 7:45:26 PM EDT
To: Jessica Neufeld <jn2434@columbia.edu>
Cc: david lounsbury <david.lounsbury@einsteinmed.org>

Hi Jessica
 
As with all things, the data we have will depend on:

- When we pulled the data and,

- Whether or not there has been any changes in the tracker such that it affects the integrity of the data we currently have.

 
I have a count of 112 active strategies for all counties from the download I pulled in response to your email (See attached the strategies spreadsheet).
This also concurs with what I had from last week.
 
Also, I have a total of 167 priority sectors (See Countif formula in Column Q in the attached Measures spreadsheet,…)
 
 
Please allow me the opportunity to run the implementation status question by Dr. Lounsbury and team.
 
 
Still herein is also my take:
 
I take it that if one wants to know the implementation status of an IPA, one would look to the # of active strategies related to a specific IPA (see column B Strategies spreadsheet). That in itself should say whether or not the IPA is specified as active.
 
Also, in Monitoring of Challenges, from a qualitatively perspective one can discern the status of an IPA and its corresponding strategies. In other words, one will learn from the data whether or not the strategy and/or IPA has been abandoned for a particular reason.
 
Now vis-à-vis the said issue, Monitoring of Measures may not be that specific but one can also see the activities related a specified IPA’s smart strategy.
 
Nonetheless, the issue you’ve raised is certainly one worth discussing further and looking into making simpler.
 
Ps. If you have any questions or detect any errors on my part, can we set up a zoom call and work through it.
I am always here for you and your team, and always open to learning from you all.
 
 
Kind  Regards
Donrie Purcell, PhD, MPH
 
Every generation has the obligation to free men's minds for a look at new worlds,....to look out from a higher plateau than the last generation.
Ellison S. Onizuka 


CONFIDENTIALITY: This email (including any attachments) may contain confidential, proprietary and/or privileged information. Any duplication, copying, distribution, dissemination, transmission, disclosure or use in any manner of this email (including any attachments) without the authorization of the sender is strictly prohibited. If you receive this email (including any attachments) in error, please notify the sender and delete this email (including any attachments) from your system. Thank you.

**Comment by dlounsbu** [comment]
From: david lounsbury 
Sent: Tuesday, September 7, 2021 10:49 PM
To: Donrie Purcell <donrie.purcell@einsteinmed.org>; Jessica Neufeld <jn2434@columbia.edu>
Subject: RE: IPA Tracker Qs

Thanks Donrie and Jessica!

I will have a look and follow up ASAP.

Best,
David

**Comment by dlounsbu** [comment]
From: david lounsbury 
Sent: Friday, September 17, 2021 4:59 PM
To: Jessica Neufeld <jn2434@columbia.edu>
Cc: Donrie Purcell <donrie.purcell@einsteinmed.org>; Nicholas Bove <nicholas.bove@einsteinmed.org>; Emma Rodgers <emr2241@columbia.edu>; Sandra Rodriguez <sr3717@columbia.edu>
Subject: Strategy Discontinue button now available

Hi Jessica:

You will notice that there is a Discontinue button on the Tracker Specification page that will you to indicate that the county has decided to end, or terminate, a Smart Strategy. 

This should address the matter of clearly indicating what IPA/Strategies are Active or Discontinued. 

Let us know how this feature serves your efforts! 

Thanks,
David
