### ISSUE TITLE
Service Request by  Emilia Camp about adding MONITORING Measures demographic data

### ISSUE THREAD

**Issue by dlounsbu** [dlounsbu/NYHEALing-IPAtracker-support#29]
- [x] Qualtrics Service Request Form was received from User
- [x] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by dlounsbu** [comment]
From: david lounsbury 
Sent: Wednesday, September 8, 2021 11:09 AM
To: Emilia.Camp@suffolkcountyny.gov
Cc: Donrie Purcell <donrie.purcell@einsteinmed.org>; Nicholas Bove <nicholas.bove@einsteinmed.org>
Subject: FW: IPA Tracker Support Request Form Submitted
Importance: High

Hi Emilia:

We have received your request and we are working on it now. 

The demographics feature is brand new. We are beta testing it now, too! 

We appreciate your reaching out!

Best and thanks,
David

**Comment by donriepurcell** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40"><p class="MsoNormal" style="margin: 0in 0in 12pt; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><b><span style="font-size: 12pt; color: black;">From:<span class="Apple-converted-space"> </span></span></b><span style="font-size: 12pt; color: black;">Jessica Neufeld &lt;jn2434@columbia.edu&gt;<br><b>Date:<span class="Apple-converted-space"> </span></b>Thursday, September 9, 2021 at 9:25 AM<br><b>To:<span class="Apple-converted-space"> </span></b>Donrie Purcell &lt;donrie.purcell@einsteinmed.org&gt;<br><b>Cc:<span class="Apple-converted-space"> </span></b>david lounsbury &lt;david.lounsbury@einsteinmed.org&gt;<br><b>Subject:<span class="Apple-converted-space"> </span></b>Re: Demographics<o:p></o:p></span></p>

CAUTION: This email comes from an external source; the attachments and/or links may compromise our secure environment. Do not open or click on suspicious emails. Please click on the “Phish Alert” button on the top right of the Outlook dashboard to report any suspicious emails.
--


<p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="color: white;">Hi Donrie, <span class="Apple-converted-space"> </span></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><o:p> </o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span>Thank you for sending along this update. <o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span>So far, the data entry makes sense and I've been able to access the demo section. I'll let you know if I run into any issues. <o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><o:p> </o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span>Thanks, <o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span>Jessica <o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><o:p> </o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span>On Wed, Sep 8, 2021 at 1:58 PM Donrie Purcell &lt;<a href="mailto:donrie.purcell@einsteinmed.org" style="color: rgb(149, 79, 114); text-decoration: underline;">donrie.purcell@einsteinmed.org</a>&gt; wrote:<o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 14pt; font-family: &quot;Times New Roman&quot;, serif;">Hi Jessica<span class="Apple-converted-space"> </span></span><o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 14pt; font-family: &quot;Times New Roman&quot;, serif;"> </span><o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 14pt; font-family: &quot;Times New Roman&quot;, serif;">I cc’d David on this email so he knows what I am up to in the tracker.</span><o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 14pt; font-family: &quot;Times New Roman&quot;, serif;"> </span><o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 14pt; font-family: &quot;Times New Roman&quot;, serif;"> </span><o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 14pt; font-family: &quot;Times New Roman&quot;, serif;">So,…Here we go;</span><o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 14pt; font-family: &quot;Times New Roman&quot;, serif;"> </span><o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 14pt; font-family: &quot;Times New Roman&quot;, serif;">The Demographics function of the IPA tracker is alive and well.</span><o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 14pt; font-family: &quot;Times New Roman&quot;, serif;"> </span><o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 14pt; font-family: &quot;Times New Roman&quot;, serif;">I worked out of Cuyaga county in the tracker, and I will have to delete the entries after figuring out how this works.</span><o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 14pt; font-family: &quot;Times New Roman&quot;, serif;"> </span><o:p></o:p></p><ol start="1" type="1" style="margin-bottom: 0in; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><li class="gmail-m2545332814928459441msolistparagraph" style="mso-list:l0 level1 lfo1;
     tab-stops:list .5in"><span style="font-size: 14pt; font-family: &quot;Times New Roman&quot;, serif;">I added a<span class="Apple-converted-space"> </span><b>Monitoring Measure</b><span class="Apple-converted-space"> </span>with a<span class="Apple-converted-space"> </span><b>Strategy<span class="Apple-converted-space"> </span></b>((B1-EP) 2.5 # of individuals receiving MOUD) that relates to a unit of measures or<span class="Apple-converted-space"> </span><b>Measure Value<span class="Apple-converted-space"> </span></b>(Persons/Individuals).</span><span><o:p></o:p></span></li><li class="gmail-m2545332814928459441msolistparagraph" style="mso-list:l0 level1 lfo1;
     tab-stops:list .5in"><span style="font-size: 14pt; font-family: &quot;Times New Roman&quot;, serif;">In this case I gave it a numerical value of<span class="Apple-converted-space"> </span><b>6</b><span class="Apple-converted-space"> </span>in the<span class="Apple-converted-space"> </span><b>Measure Value</b><span class="Apple-converted-space"> </span>section.<span class="Apple-converted-space"> </span></span><span><o:p></o:p></span></li><li class="gmail-m2545332814928459441msolistparagraph" style="mso-list:l0 level1 lfo1;
     tab-stops:list .5in"><span style="font-size: 14pt; font-family: &quot;Times New Roman&quot;, serif;">This data will automatically move to the<span class="Apple-converted-space"> </span><b>Measure Monitoring History</b><span class="Apple-converted-space"> </span>if one clicks the<span class="Apple-converted-space"> </span><b>Save</b>icon.</span><span><o:p></o:p></span></li><li class="gmail-m2545332814928459441msolistparagraph" style="mso-list:l0 level1 lfo1;
     tab-stops:list .5in"><span style="font-size: 14pt; font-family: &quot;Times New Roman&quot;, serif;">Thereafter click on<span class="Apple-converted-space"> </span><b>Show Demographics</b><span class="Apple-converted-space"> </span>and select<span class="Apple-converted-space"> </span><b>Race/Ethnicity</b><span class="Apple-converted-space"> </span>or<span class="Apple-converted-space"> </span><b>Gender</b><span class="Apple-converted-space"> </span>or<span class="Apple-converted-space"> </span><b>Age Groups</b>. In this case I chose<span class="Apple-converted-space"> </span><b>Race/Ethnicity.<span class="Apple-converted-space"> </span></b></span><span><o:p></o:p></span></li><li class="gmail-m2545332814928459441msolistparagraph" style="mso-list:l0 level1 lfo1;
     tab-stops:list .5in"><span style="font-size: 14pt; font-family: &quot;Times New Roman&quot;, serif;">Then click on the strategy and select<span class="Apple-converted-space"> </span><b>(B1-EP),<span class="Apple-converted-space"> </span></b>then click on<span class="Apple-converted-space"> </span><b>Measure</b><span class="Apple-converted-space"> </span>and select<span class="Apple-converted-space"> </span><b>2.5 # of individuals receiving MOUD<span class="Apple-converted-space"> </span></b>and select<span class="Apple-converted-space"> </span><b>Apply</b></span><span><o:p></o:p></span></li><li class="gmail-m2545332814928459441msolistparagraph" style="mso-list:l0 level1 lfo1;
     tab-stops:list .5in"><span style="font-size: 14pt; font-family: &quot;Times New Roman&quot;, serif;">Thereafter, select<span class="Apple-converted-space"> </span><b>Edit<span class="Apple-converted-space"> </span></b>to your left and therein you will find the options to enter as shown on screen shot #2 .</span><span><o:p></o:p></span></li><li class="gmail-m2545332814928459441msolistparagraph" style="mso-list:l0 level1 lfo1;
     tab-stops:list .5in"><span style="font-size: 14pt; font-family: &quot;Times New Roman&quot;, serif;">After you finish with your selections you click<span class="Apple-converted-space"> </span><b>ok<span class="Apple-converted-space"> </span></b>and you will see same results as in screen shot # 3.</span><span><o:p></o:p></span></li></ol><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><b><span style="font-size: 14pt; font-family: &quot;Times New Roman&quot;, serif;"> </span></b><o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 14pt; font-family: &quot;Times New Roman&quot;, serif;">Jessica, I hope this makes sense. I am here for a zoom call whenever you wish to. I am going to delete the pseudo entries from the tracker. Give it a shot and let me know how you feel about it.</span><o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 14pt; font-family: &quot;Times New Roman&quot;, serif;"> </span><o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 14pt; font-family: &quot;Times New Roman&quot;, serif;"> </span><o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; vertical-align: baseline;"><span style="font-size: 14pt; font-family: &quot;Times New Roman&quot;, serif; color: black;">Regards<br>Donrie Purcell, PhD, MPH</span><o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; vertical-align: baseline;"><span style="font-size: 14pt; font-family: &quot;Times New Roman&quot;, serif; color: black;"> </span><o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; vertical-align: baseline;"><span style="font-size: 14pt; font-family: &quot;Times New Roman&quot;, serif; color: black;">Every generation has the obligation to free men's minds for a look at new worlds,....to look out from a higher plateau than the last generation.<br>Ellison S. Onizuka <br><br><br>CONFIDENTIALITY: This email (including any attachments) may contain confidential, proprietary and/or privileged information. Any duplication, copying, distribution, dissemination, transmission, disclosure or use in any manner of this email (including any attachments) without the authorization of the sender is strictly prohibited. If you receive this email (including any attachments) in error, please notify the sender and delete this email (including any attachments) from your system. Thank you.</span><o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 14pt; font-family: &quot;Times New Roman&quot;, serif;"> </span><o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 14pt; font-family: &quot;Times New Roman&quot;, serif;"> </span><o:p></o:p></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><br clear="all"><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><o:p> </o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span>--<span class="Apple-converted-space"> </span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><o:p> </o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><b><span style="font-family: Arial, sans-serif; color: black;">Jessica Neufeld, MPH</span></b><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-family: Arial, sans-serif; color: black;">Program Manager </span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-family: Arial, sans-serif; color: black;">HEALing Communities Study</span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-family: Arial, sans-serif; color: black;">Social Intervention Group</span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-family: Arial, sans-serif; color: black;"><span style="font-stretch: normal;">Columbia University School of Social Work</span><br style="font-stretch: normal; overflow: visible;"><span style="font-stretch: normal;">1255 Amsterdam Avenue</span></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-family: Arial, sans-serif; color: black;">New York, NY 10027</span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><a href="mailto:jn2434@columbia.edu" target="_blank" style="color: rgb(149, 79, 114); text-decoration: underline;">jn2434@columbia.edu</a>  <o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-family: Arial, sans-serif; color: rgb(34, 34, 34);">Website: </span><span style="font-family: Arial, sans-serif;"> </span><span><a href="https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsig.columbia.edu%2F&amp;data=04%7C01%7Cdonrie.purcell%40einsteinmed.org%7C13c7ac5b03984661699408d973953fb9%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637667907124536656%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=ZhKnl4nuww6de6JMPdIbbE7f3DOuP4g6VcQPT3yIohA%3D&amp;reserved=0" target="_blank" style="color: rgb(149, 79, 114); text-decoration: underline;"><span style="font-family: Arial, sans-serif; color: rgb(17, 85, 204);">https://sig.columbia.edu/</span></a><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><o:p> </o:p></span></p></html>
