### ISSUE TITLE
Support Request by Anna N. Weiskopf

### ISSUE THREAD

**Issue by dlounsbu** [dlounsbu/NYHEALing-IPAtracker-support#3]
- [ ] Qualtrics Service Request Form was received from User
- [x] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [x] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by dlounsbu** [comment]
![Anna snip](https://user-images.githubusercontent.com/20574023/128562536-f739a5f0-2622-4ae6-8e29-a6e57ee95376.png)

**Comment by donriepurcell** [comment]
I met with Anna and explained the need for unique identifiers within the IPA Tracker and she got it.
Also, she kind asked if wed can have the following in the IPA TRACKER:

1.  An automatic save function within the IPA TRACKER
2. 15 mins leeway before the system shuts down
3. A countdown for the tracker within 2 to 5 mins of close

**Comment by dlounsbu** [comment]
Hi Donrie: 

For Anna, let's ask Jeff about how saving works. I think that information is automating saved, or think about how to give better on saving tips. 

I personally like that one is automatically logged out after 15 mins. It is easy to go back into the systems if that happens, because the home page should remember the user and her password. 

Yes, let's ask Jeff to add the feature that prompt people about the system logging the off. If it is not expensive, maybe he can add that.

**Comment by dlounsbu** [comment]
<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=Edit-Time-Data
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_editdata.mso">

<link rel=themeData
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link=blue vlink="#954F72" style='tab-interval:.5in'>


<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
mso-ascii-theme-font:minor-latin;mso-hansi-theme-font:minor-latin;mso-bidi-font-family:
"Times New Roman";mso-bidi-theme-font:minor-bidi;color:#1F497D'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
mso-ascii-theme-font:minor-latin;mso-hansi-theme-font:minor-latin;mso-bidi-font-family:
"Times New Roman";mso-bidi-theme-font:minor-bidi;color:#1F497D'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><a name="_MailOriginal"><b><span style='font-size:11.0pt;
font-family:"Calibri",sans-serif;mso-fareast-font-family:"Times New Roman"'>From:</span></b></a><span
style='mso-bookmark:_MailOriginal'><span style='font-size:11.0pt;font-family:
"Calibri",sans-serif;mso-fareast-font-family:"Times New Roman"'> Anna N.
Weiskopf [mailto:aw3391@columbia.edu] <br>
<b>Sent:</b> Thursday, August 5, 2021 2:31 PM<br>
<b>To:</b> Donrie Purcell &lt;donrie.purcell@einsteinmed.org&gt;<br>
<b>Cc:</b> Emma Rodgers &lt;emr2241@columbia.edu&gt;; david lounsbury
&lt;david.lounsbury@einsteinmed.org&gt;; Anika Buch
&lt;ambuch@princeton.edu&gt;; Nicholas Bove
&lt;nicholas.bove@einsteinmed.org&gt;<br>
<b>Subject:</b> Re: IPA Reporting Tracker<o:p></o:p></span></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'><o:p>&nbsp;</o:p></span></p>



CAUTION: This email comes from an external   source; the attachments and/or links may compromise our secure environment.   Do not open or click on suspicious emails. Please click on the “Phish Alert”   button on the top right of the Outlook dashboard to report any suspicious   emails.
--




<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><span style='color:white'>Hi Donrie,</span><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>One other thing, I keep going in and making
changes and hitting 'save all'. However, when I go back to view my changes,
they either aren't there, aren't changed, or saved in the wrong&nbsp;place. Do
you know why this is happening?<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>Thanks,<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>Anna<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>On Thu, Aug 5, 2021 at 9:52 AM Anna N.
Weiskopf &lt;</span><a href="mailto:aw3391@columbia.edu" target="_blank"><span
style='mso-bookmark:_MailOriginal'>aw3391@columbia.edu</span><span
style='mso-bookmark:_MailOriginal'></span></a><span style='mso-bookmark:_MailOriginal'>&gt;
wrote:<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>Hi Donrie,<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>I hope you are having a nice morning. I am
going through the IPA tracker and inputting data for Cayuga. Under 'measures'
and then 'Measure Reporting Frequency', I don't see an option for sporadic
reporting. Would it be possible to add that to the tracker? <o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>Thank you,<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>Anna<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>-- <o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><b>Anna Weiskopf</b></span><span
style='mso-bookmark:_MailOriginal'><b><span style='font-family:"Arial",sans-serif'>,
MPA</span></b><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><i>Research Coordinator</i><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>Social Intervention Group, HEALing
Communities Study<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>Columbia University School of Social Work<br>
1255 Amsterdam Avenue, Suite 807<br>
New York, NY 10027<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>Email: </span><a
href="mailto:aw3391@columbia.edu" target="_blank"><span style='mso-bookmark:
_MailOriginal'>aw3391@columbia.edu</span><span style='mso-bookmark:_MailOriginal'></span></a><span
style='mso-bookmark:_MailOriginal'><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>Cell: 212-853-7053 <o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>Website: </span><a
href="https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsig.columbia.edu%2F&amp;data=04%7C01%7Cdavid.lounsbury%40einsteinmed.org%7C219219e5f940483ae18408d9583f44f6%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637637851045111654%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=%2FjCKQgZT0g0cEEVjgyjMX0KjwlMSVATeBH1eEXkKxYg%3D&amp;reserved=0"
target="_blank" originalsrc="https://sig.columbia.edu/"
shash="AbNVPr36aMxh3DkNENsxQg3G2QcUerEInSJdDRGi3zuaf3uJl4975L3wnQlbitYouhPsRuh3epFkGjHejyh+Cg2VSnx2RrU61bzhwQMM3FXhwfDxiszNK7zvfHtOwreKfICsspLYTxcm4aNMgVayvO8O65fJVLmWU1bRb8/WaYc="><span
style='mso-bookmark:_MailOriginal'>https://sig.columbia.edu/</span><span
style='mso-bookmark:_MailOriginal'></span></a><span style='mso-bookmark:_MailOriginal'><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><br clear=all>
<br>
-- <o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><b>Anna Weiskopf</b></span><span
style='mso-bookmark:_MailOriginal'><b><span style='font-family:"Arial",sans-serif'>,
MPA</span></b><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'><i>Research Coordinator</i><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>Social Intervention Group, HEALing
Communities Study<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>Columbia University School of Social Work<br>
1255 Amsterdam Avenue, Suite 807<br>
New York, NY 10027<o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>Email: </span><a
href="mailto:aw3391@columbia.edu" target="_blank"><span style='mso-bookmark:
_MailOriginal'>aw3391@columbia.edu</span><span style='mso-bookmark:_MailOriginal'></span></a><span
style='mso-bookmark:_MailOriginal'><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>Cell: 212-853-7053 <o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>Website: </span><a
href="https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsig.columbia.edu%2F&amp;data=04%7C01%7Cdavid.lounsbury%40einsteinmed.org%7C219219e5f940483ae18408d9583f44f6%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637637851045121614%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=x74%2F%2BTE8i7H%2FTmBWuuTPj8t8mVt2m8xHSlbUJ3hi3Ss%3D&amp;reserved=0"
target="_blank" originalsrc="https://sig.columbia.edu/"
shash="TnV2onMH3Ut1Hp/q4XwJiTczuh6c4DDbr6o1Vu0EyLQ1tOrPgNsN5ccGbsvk3rYUwJeGuaCsFHmNGAvFWKVjZWzdyWZD4x2BA3VyGkcFbPgRk+mGGw7X19vkqy2tfQK3EZo4JIajN4NK4mSjsVn95Y7UYApqY8pT6XrldQDcbdM="><span
style='mso-bookmark:_MailOriginal'>https://sig.columbia.edu/</span><span
style='mso-bookmark:_MailOriginal'></span></a><span style='mso-bookmark:_MailOriginal'><o:p></o:p></span></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='mso-bookmark:_MailOriginal'>&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'><span
style='mso-fareast-font-family:"Times New Roman"'><br clear=all>
<br>
-- <o:p></o:p></span></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'><b><span
style='mso-fareast-font-family:"Times New Roman"'>Anna Weiskopf</span></b></span><span
style='mso-bookmark:_MailOriginal'><b><span style='font-family:"Arial",sans-serif;
mso-fareast-font-family:"Times New Roman"'>, MPA</span></b></span><span
style='mso-bookmark:_MailOriginal'><span style='mso-fareast-font-family:"Times New Roman"'><o:p></o:p></span></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'><i><span
style='mso-fareast-font-family:"Times New Roman"'>Research Coordinator</span></i></span><span
style='mso-bookmark:_MailOriginal'><span style='mso-fareast-font-family:"Times New Roman"'><o:p></o:p></span></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'><span
style='mso-fareast-font-family:"Times New Roman"'>Social Intervention Group,
HEALing Communities Study<o:p></o:p></span></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'><span
style='mso-fareast-font-family:"Times New Roman"'>Columbia University School of
Social Work<br>
1255 Amsterdam Avenue, Suite 807<br>
New York, NY 10027<o:p></o:p></span></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'><span
style='mso-fareast-font-family:"Times New Roman"'>Email: </span></span><a
href="mailto:aw3391@columbia.edu" target="_blank"><span style='mso-bookmark:
_MailOriginal'><span style='mso-fareast-font-family:"Times New Roman"'>aw3391@columbia.edu</span></span><span
style='mso-bookmark:_MailOriginal'></span></a><span style='mso-bookmark:_MailOriginal'><span
style='mso-fareast-font-family:"Times New Roman"'><o:p></o:p></span></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'><span
style='mso-fareast-font-family:"Times New Roman"'>Cell: 212-853-7053 <o:p></o:p></span></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'><span
style='mso-fareast-font-family:"Times New Roman"'>Website: </span></span><a
href="https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsig.columbia.edu%2F&amp;data=04%7C01%7Cdavid.lounsbury%40einsteinmed.org%7C219219e5f940483ae18408d9583f44f6%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637637851045131579%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=v0ap%2Fqrx9HRWFly4dltmWr8iARxPBWEEn7T7kU0qP3k%3D&amp;reserved=0"
target="_blank" originalsrc="https://sig.columbia.edu/"
shash="y3O2nOw80Gm0ethLDr6we5P/31+I3c8z3GLNLLYMl8EWbu8Ti4Dtf81OLGy9o8KWYilEfsCJKuiTpcpTNTSk0P24pP4CaRHB59YieUnXT+vk1pQSH2H2sakYtVfHp4J/NFcY1/MHxva1rDi8+Cc+Cy82Kqn8oRrEYwU8khBkKtQ="><span
style='mso-bookmark:_MailOriginal'><span style='mso-fareast-font-family:"Times New Roman"'>https://sig.columbia.edu/</span></span><span
style='mso-bookmark:_MailOriginal'></span></a><span style='mso-bookmark:_MailOriginal'><span
style='mso-fareast-font-family:"Times New Roman"'><o:p></o:p></span></span></p>

<span style='mso-bookmark:_MailOriginal'></span>

<p class=MsoNormal><span style='mso-fareast-font-family:"Times New Roman"'><o:p>&nbsp;</o:p></span></p>


</body>
This was a copy of Anna's original e-mail

</html>

[Anna W](https://user-images.githubusercontent.com/20574023/128562362-03478725-0e4a-49a8-9247-1c25f3fe20a0.PNG)

**Comment by dlounsbu** [comment]
I think we can close this issue, but we will follow up with Jeff to see if we can/should add a note about impending auto log out from the Tracker. Personally, I do that think this is a priority feature to add.
