### ISSUE TITLE
Service Request by David Lounsbury about programming Units for 'Other' measures

### ISSUE THREAD

**Issue by dlounsbu** [dlounsbu/NYHEALing-IPAtracker-support#35]
- [ ] Problem NOT RESOLVED
- [x] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by dlounsbu** [comment]
![Other check](https://user-images.githubusercontent.com/20574023/132920055-20bdd128-ce9b-4b89-9404-013c787b763d.JPG)

@jbazinet1111 Can you help us figure out a way to better units for Other measures? 

Currently, I think any user can and an Other measure of their own, but that feature does not prompt for 'Units'. 

Maybe we should only allow Administrators to ADD/define Other measures?  Can that be arranged? 

Even if we use List Options to edit units for Other measures, it does not seem to properly update data in the Tracker. 

Thoughts?

Best,
David

**Comment by jbazinet1111** [comment]
First, let me see if we have a bug with the units in List Options. If that is working fine, then perhaps we can force the users in that direction.

**Comment by jbazinet1111** [comment]
So there is only a single OTHER MEASURE defined within the list options and it is for Expand MOUD Availability.

I would suggest that perhaps there should be others defined within the Options (which is Admin only) such that the units are clearly set up.

Maybe look at what the users have typed in as their "other measures" in the ad-hoc specifications process and create the same measures (w/ units) in the Options. That might make things easier for everyone.

If that doesn't seem feasible then we can look at alternatives but since that functionality is already there, we might as well try it.

**Comment by dlounsbu** [comment]
This issue links with #39, too. 

DL

**Comment by dlounsbu** [comment]
I think we may need to restrict users from ADDING a new 'Other' measure. Somehow, we need to inform users that, to add an other measure, they need to send a Tracker TA Service request, or find someone with Admin privileges who would know to add the Other measure and update the units for it. 

@jbazinet1111 What do you advise to address this matter?

**Comment by jbazinet1111** [comment]
This would certainly work. Removing that functionality we built previously will take about a two hours of effort.

**Comment by dlounsbu** [comment]
Very good! Okay, let's go with this! 

THANK YOU Jeff

**Comment by jbazinet1111** [comment]
This has been deployed

**Comment by dlounsbu** [comment]
Thanks Jeff! 

Donrie and Nick, we need to document the Discontinue (a strategy) feature in our User's Manual. #2

**Comment by NBOVE1** [comment]
@jbazinet1111 Since the tracker has been back online we seem to be getting a bug across all counties when entering data in measures monitoring:
https://github.com/dlounsbu/NYHEALing-IPAtracker-support/issues/35#issuecomment-954847249

**Comment by dlounsbu** [comment]
Thanks for this note! I hope we can resolve this ASAP.

**Comment by jbazinet1111** [comment]
What bug?

**Comment by NBOVE1** [comment]
This looks to be resolved, thanks Jeff!

**Comment by dlounsbu** [comment]
thanks all.

DL
