### ISSUE TITLE
Service Request by Jessica to ad the NR variable to the demographic options 

### ISSUE THREAD

**Issue by donriepurcell** [dlounsbu/NYHEALing-IPAtracker-support#36]
- [ ] Qualtrics Service Request Form was received from User
- [ ] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by donriepurcell** [comment]
From: Jessica Neufeld <jn2434@columbia.edu>
Subject: Re: Demographics
Date: September 13, 2021 at 10:24:59 AM EDT
To: david lounsbury <david.lounsbury@einsteinmed.org>
Cc: Donrie Purcell <donrie.purcell@einsteinmed.org>

Hi Donrie and David,  

 

I think one or two demographic values are missing. I've bolded the ones I didn't see in the Tracker. 

 

Biological Sex: (4 options: Male, Female, Other [to include non-binary], NR); 

Race/Ethnicity: (7 options : Hispanic, Non-Hispanic-Black, Non-Hispanic-White, Non-Hispanic-Other,Asian, More than one race, NR); and 

Age Group: (5 options : Less than 18, 18-34, 35-54, 55+, NR). 

 

Best,

Jessica

**Comment by donriepurcell** [comment]
Hi Jeff,
We previously added the option ourselves but it is not showing up in the IPA Monitoring section.
Please see screen shots and advise,.. 

<img width="1237" alt="Screen Shot 2021-09-13 at 11 15 51 AM" src="https://user-images.githubusercontent.com/80912517/133111359-e8c84e92-ca8b-4f32-a59a-982dad30d7b9.png">

<img width="1171" alt="Screen Shot 2021-09-13 at 11 14 00 AM" src="https://user-images.githubusercontent.com/80912517/133111477-129ef0c5-df01-4b41-a726-978fda4aebce.png">

**Comment by jbazinet1111** [comment]
These should be in place now.

**Comment by donriepurcell** [comment]
Hi Jeff
Thanks
