### ISSUE TITLE
Service Request by Monika Salvage for Milestones Data coherence sorting

### ISSUE THREAD

**Issue by donriepurcell** [dlounsbu/NYHEALing-IPAtracker-support#37]
- [x] Qualtrics Service Request Form was received from User
- [x] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by donriepurcell** [comment]
Hi Jeff,

Monika raised the issue of her data being "disorganized under mIlestones in specification".
I know you worked on this before. Please can you help the counties in general writing a code so that these Milestones are all sorted by intended start date.
Thanks 
Donrie

**Comment by dlounsbu** [comment]
Yes, Jeff fixed this in Monitoring Milestones, but maybe in Specification. 

Jeff, please add your sort feature to Specification, too.

**Comment by jbazinet1111** [comment]
Can you tell me the county/IPA/Strategy for this? 

In the code, Milestones in Specification is already sorted by IntendedStart date.
Perhaps I'm missing something.

**Comment by donriepurcell** [comment]
The county in question was Cayuga County 

<img width="1237" alt="Screen Shot 2021-09-13 at 1 59 33 PM" src="https://user-images.githubusercontent.com/80912517/133149530-8e673bee-39d9-468c-9939-5a44b27bea7a.png">

**Comment by dlounsbu** [comment]
Hi Jeff: 

Cayuga. Looks like Milestone Monitoring is fine. Maybe an issue in Specification. 

DL

**Comment by jbazinet1111** [comment]
I found it. This should be all set now.

**Comment by dlounsbu** [comment]
Thanks! Great.
