### ISSUE TITLE
Service Request by Monika Salvage about replicating another county's smart strategy in their county.

### ISSUE THREAD

**Issue by dlounsbu** [dlounsbu/NYHEALing-IPAtracker-support#38]
- [ ] Qualtrics Service Request Form was received from User
- [ ] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by dlounsbu** [comment]
From: David Lounsbury [mailto:noreply@qemailserver.com] 
Sent: Monday, September 13, 2021 2:28 PM
To: david lounsbury <david.lounsbury@einsteinmed.org>
Subject: IPA Tracker Support Request Form Submitted 

IPA SERVICE REQUEST SUMMARY


1. CONTACT INFORMATION:

Monika  Salvage

Email:  msalvage@cayugacounty.us

Phone:  3152531522


2. COUNTY

Cayuga


3. WHICH FEATURE(S):

SPECIFICATION: Creating, updating, deleting information to define or describe a SMART Strategy


4. BRIEF PROBLEM DESCRIPTION:

Could you copy the pharmacy conference strategy from Columbia County over to Cayuga County with a unique name, such as Pharmacy Conference Cayuga and then we would adapt it for our county? Thanks.


5. URGENCY:

75


6. ANYTHING ELSE TO SHARE:

**Comment by dlounsbu** [comment]
From: david lounsbury 
Sent: Monday, September 13, 2021 3:26 PM
To: Monika Salvage <msalvage@cayugacounty.us>
Cc: Donrie Purcell <donrie.purcell@einsteinmed.org>
Subject: RE: IPA Tracker Support Request Form Submitted

Got it. 

So, we will look to see which strategies to download the data from Columbia, and then we can work with you to enter it for Cayuga.

DL



From: Monika Salvage [mailto:msalvage@cayugacounty.us] 
Sent: Monday, September 13, 2021 3:16 PM
To: david lounsbury <david.lounsbury@einsteinmed.org>
Subject: RE: IPA Tracker Support Request Form Submitted

There are four counties that collaborated to put together this pharmacy conference, so basically the milestones and everything would be the same. 

Monika 

MONIKA SALVAGE 
Project Director 
(315) 253-1522 

HEALing Communities Study 
Helping to End Addiction Long-term 
cayugacounty.us/healingcayuga 

From: david lounsbury <david.lounsbury@einsteinmed.org> 
Sent: Monday, September 13, 2021 3:14 PM
To: Monika Salvage <msalvage@cayugacounty.us>
Cc: Donrie Purcell <donrie.purcell@einsteinmed.org>
Subject: FW: IPA Tracker Support Request Form Submitted 

Hi Monika: 

This is an interesting request. 

What we could to do is download that information for the strategy you are referring to and send it to you. 

You could use the download data to help you add a new IPA/Strategy to Cayuga’s portfolio. 

I am curious, how did you come to learn about Columbia’s strategy?? 

Just left you a voice message about this, too! 
DL

**Comment by dlounsbu** [comment]
@donriepurcell 

I think that we should just do this for Monika. Should not take too much time.  

We need to make sure we know which strategy she is referring to in Columbia.

Thank you,
David

**Comment by donriepurcell** [comment]
From: donriepurcell <donrie.purcell@einsteinmed.org>
Subject: Completion of the IPA data entry
Date: September 14, 2021 at 10:14:19 PM EDT
To: msalvage@cayugacounty.us
Cc: david lounsbury <david.lounsbury@einsteinmed.org>, Nasim Sabounchi <Nasim.Sabounchi@sph.cuny.edu>, weiskopf Anna <aw3391@columbia.edu>, Nicholas Bove <nicholas.bove@einsteinmed.org>

Hi Monika

Please be aware that I found the IPA you referred to in the last meeting and I have entered the data collected from the Columbia County IPA into Cayuga County as a replica IPA.
Also, please note that it can be found in Safer Prescribing under the Smart Strategy C3-County Collaboration. Off Course, there may be subsequent edits that you may find appropriate to make at any time.

Regards 
Donrie J.R. Purcell, PhD, MPH

Every generation has the obligation to free men's minds for a look at new worlds,....to look out from a higher plateau than the last generation.
Ellison S. Onizuka  


CONFIDENTIALITY: This email (including any attachments) may contain confidential, proprietary and/or privileged information. Any duplication, copying, distribution, dissemination, transmission, disclosure or use in any manner of this email (including any attachments) without the authorization of the sender is strictly prohibited. If you receive this email (including any attachments) in error, please notify the sender and delete this email (including any attachments) from your system. Thank you.

![image](https://user-images.githubusercontent.com/80912517/133359505-9682039d-6cce-464e-ad4b-205e12adc51e.png)

**Comment by dlounsbu** [comment]
Thanks for taking the time to do this for Monika, Donrie. 

I know this turned into a lot of work, and that Monika and other county staff should have and could have entered this themselves. 

We are still coming to terms about our role and responsibility relative to the county's, relative to Columbia staff. 

Anything we can do to clarify and document these will be useful moving forward.
