### ISSUE TITLE
Service Request by Corinna to change the Unit of Measure from Venues to Persons for "# of individual initiated onto interim buprenorphine"

### ISSUE THREAD

**Issue by donriepurcell** [dlounsbu/NYHEALing-IPAtracker-support#39]
- [x] Qualtrics Service Request Form was received from User
- [x] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by donriepurcell** [comment]
IPA SERVICE REQUEST SUMMARY


1. CONTACT INFORMATION:

Corinna  Noel

Email:  can64@cornell.edu

Phone:  8459017114


2. COUNTY

Cayuga


3. WHICH FEATURE(S):

MONITORING: Creating, updated or deleting information about an implemented SMART Strategy


4. BRIEF PROBLEM DESCRIPTION:

Hi -- This is not a request for direct support but wanted to point out an error in the IPA tracker system related to measures/monitoring. For our B1 MOUD expansion strategies, one of the primary measures you can choose from in the drop down menu is is "# of individual initiated onto interim buprenorphine". When this is selected, and filled in via the monitoring section, the units automatically complete to "venues" instead of "persons". This is in contrast to the similar primary measure "# of individuals initiated onto interim methadone" where the units are correctly "persons". This is not urgent but would be helpful if you could fix on your end so that our data is not misinterpreted. Thanks!


5. URGENCY:

0


6. ANYTHING ELSE TO SHARE:

**Comment by donriepurcell** [comment]
Hi Jeff 
I tried making the change myself by updating the change in options. However, when I went back to Monitoring Measures that change was not reflected in the data or new data that I tried entering as a test.

<img width="1265" alt="Screen Shot 2021-09-15 at 10 25 16 AM" src="https://user-images.githubusercontent.com/80912517/133455446-d5b4c47a-4992-41e2-b8bb-8ebc25410908.png">
.

**Comment by dlounsbu** [comment]
Hi Donrie:

Did you email Corinna to let her now we received her message and that we are working on it? 

@jbazinet1111 

What do you advise? Is this a bug or how can we handle this matter?   

DL

**Comment by donriepurcell** [comment]
Hi Profe,
I actually called her.
Regards
Donrie J.R. Purcell, PhD, MPH

Every generation has the obligation to free men's minds for a look at new worlds,....to look out from a higher plateau than the last generation.
Ellison S. Onizuka


CONFIDENTIALITY: This email (including any attachments) may contain confidential, proprietary and/or privileged information. Any duplication, copying, distribution, dissemination, transmission, disclosure or use in any manner of this email (including any attachments) without the authorization of the sender is strictly prohibited. If you receive this email (including any attachments) in error, please notify the sender and delete this email (including any attachments) from your system. Thank you.

On Sep 15, 2021, at 5:05 PM, David W Lounsbury ***@***.******@***.***>> wrote:

CAUTION: This email comes from an external source; the attachments and/or links may compromise our secure environment. Do not open or click on suspicious emails. Please click on the “Phish Alert” button on the top right of the Outlook dashboard to report any suspicious emails.


Hi Donrie:

Did you email Corinna to let her now we received her message and that we are working on it?

@jbazinet1111<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjbazinet1111&data=04%7C01%7Cdonrie.purcell%40einsteinmed.org%7Cdef4b377fd7543a70fbb08d9788c8b21%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637673367303738064%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4oKI%2FJ9SJTcH9%2F%2B5KKJnTNk5QXvBV0zERy0G7grljsI%3D&reserved=0>

What do you advise? Is this a bug or how can we handle this matter?

DL

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdlounsbu%2FNYHEALing-IPAtracker-support%2Fissues%2F39%23issuecomment-920375167&data=04%7C01%7Cdonrie.purcell%40einsteinmed.org%7Cdef4b377fd7543a70fbb08d9788c8b21%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637673367303748058%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1dWi3F7mcKCqsCvSwYQ98maJFMOf%2BcF9KqQEd0XOGhE%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATJKBBNKOQLNZRVAZWRR623UCEDBNANCNFSM5ECTV7KQ&data=04%7C01%7Cdonrie.purcell%40einsteinmed.org%7Cdef4b377fd7543a70fbb08d9788c8b21%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637673367303758052%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0MwFEIcp%2By7zunf1bcnrFkysxlYYMbu9x1nHLlJ4wDw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cdonrie.purcell%40einsteinmed.org%7Cdef4b377fd7543a70fbb08d9788c8b21%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637673367303758052%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2Fk3dNoxF%2B9PgaUM%2F1GzzehEd%2Bzd5QUNv704n02N1poo%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cdonrie.purcell%40einsteinmed.org%7Cdef4b377fd7543a70fbb08d9788c8b21%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637673367303768047%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yx9XJwCfihuWjG%2BNU%2FwpIqMjv7kjycQZmxBdCSlilC0%3D&reserved=0>.

**Comment by jbazinet1111** [comment]
This is by design. We can make it update both the Monitoring and the exiting strategy specification if you'd like.
I guess the concern here when it was built was that people will have entered data for monitoring but then you are changing the units and the monitoring data that had already existed may not be applicable.

If you created a new strategy in Specifications, you will see the Persons unit of measure.

If (as in this case) it is just an error, I can update the value in all the database tables.

But if you aren't concerned with changing the units of measure when data already exists, then I can adjust the underlying code.

**Comment by dlounsbu** [comment]
> This is by design. We can make it update both the Monitoring and the exiting strategy specification if you'd like.
> I guess the concern here when it was built was that people will have entered data for monitoring but then you are changing the units and the monitoring data that had already existed may not be applicable.
> 
> If you created a new strategy in Specifications, you will see the Persons unit of measure.
> 
> If (as in this case) it is just an error, I can update the value in all the database tables.
> 
> But if you aren't concerned with changing the units of measure when data already exists, then I can adjust the underlying code.

Hi Jeff: 

Yes, in this case the units were somehow wrong to begin with, so updating the units in all database tables makes sense. 

From an Administrator's perspective, I think that being able to change the label for a measure and/or its units from List Options, and to know that it will automatically (or maybe as a second Admin task) run a 'patch' to update all databases tables, would be ideal. 

Thoughts? 

THANKS,
David

**Comment by donriepurcell** [comment]
Hi Jeff

I just reminded to check the monitoring section and **"# of individual initiated onto interim buprenorphine"** still is the unit of measurement for **Venues**. 
If possible can you take a quick look at it, change the previous units of measurements, and also change it so that Persons are the unit of measurement.
It appears that it may be causing some degree of consternation in the community that we have not fix the request as yet.
Jeff, thanks again for all you do.

Regards 
Donrie

**Comment by jbazinet1111** [comment]
This has been manually updated in the database.

**Comment by jbazinet1111** [comment]
The code has been changed to retroactively update specifications and monitoring of all existing records if you change the units of measure.

**Comment by dlounsbu** [comment]
Excellent.

**Comment by donriepurcell** [comment]
Thanks Jeff
