### ISSUE TITLE
Service Request by Emilia Camp about MONITORING data entry for a SMART Strategy

### ISSUE THREAD

**Issue by dlounsbu** [dlounsbu/NYHEALing-IPAtracker-support#40]
- [x] Qualtrics Service Request Form was received from User
- [x] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

From: David Lounsbury [mailto:noreply@qemailserver.com] 
Sent: Thursday, September 16, 2021 2:14 PM
To: david lounsbury <david.lounsbury@einsteinmed.org>
Subject: IPA Tracker Support Request Form Submitted

**IPA SERVICE REQUEST SUMMARY

1. CONTACT INFORMATION:

Emilia  Camp

Email:  emilia.camp@suffolkcountyny.gov

Phone:  6318538137

2. COUNTY

Suffolk

3. WHICH FEATURE(S):

MONITORING: Creating, updated or deleting information about an implemented SMART Strategy

4. BRIEF PROBLEM DESCRIPTION:

I am having an issue with updating the IPA tracking. When I clicked on measure history, the drop down (measure) doesn't link to the measure on the form below (measure monitoring/edit-delete). When I update the measure, it will update ALL selections. 

5. URGENCY:

50

6. ANYTHING ELSE TO SHARE:**

**Comment by dlounsbu** [comment]
From: david lounsbury 
Sent: Thursday, September 16, 2021 3:09 PM
To: emilia.camp@suffolkcountyny.gov
Cc: Donrie Purcell <donrie.purcell@einsteinmed.org>; Nicholas Bove <nicholas.bove@einsteinmed.org>
Subject: FW: IPA Tracker Support Request Form Submitted

Hi Emilia:

We have received your request. 

A short Zoom meeting to see exactly what you are describing may be useful. 

[Donrie or Nick, please follow up with Emilia]

Best,
David

**Comment by NBOVE1** [comment]
Hi All,
I've just met with Emilia. It seems as if within IPA MONITORING, when entering measures data, it was not generating under measure monitoring history. Further, she was unable to update demographics. I've just opened up the IPA we were reviewing (OEND Fast Track) and I seem to be able to update the monitoring section without any issues. Could it perhaps be an admin vs Suffolk user issue?

![image](https://user-images.githubusercontent.com/88558561/133678455-edb9dbbf-fd8f-46b8-9f3c-c84aa1cf49bf.png)

**Comment by donriepurcell** [comment]
Hi Nick,
Great work, I was awaiting a 4 o clock meeting. No worries & thanks for all your efforts.
Donrie

**Comment by NBOVE1** [comment]
No problem Donrie. Yes, it's not resolved yet. I had Emilia share her screen and it was clear that she was not able to update data in "Measure Monitoring History"

**Comment by dlounsbu** [comment]
Interesting. We will await Jeff's review of the matter.

**Comment by dlounsbu** [comment]
> Interesting. We will await Jeff's review of the matter.

@jbazinet1111 Please have a look. @NBOVE1 thinks it may be a user access issue.

DL

**Comment by jbazinet1111** [comment]
There is no differentiation between admin vs user in this scenario.
Can you document the steps she is taking? (w/ screen shot?)

**Comment by dlounsbu** [comment]
@NBOVE1 When you have a moment, can you provide more information about this issue?

Ask Emilia about the browser she is using. Could that be the issue?

Also, should we try to delete her username and password, and then re-add it? Could that be the issue?

**Comment by NBOVE1** [comment]
Hi David,
Yes, I'm working around Emilia's schedule today to touch base and further work on this issue. I'll check the browser and re-add her username. I'll report back with an update right after our meeting.
Thanks!
Nick

**Comment by jbazinet1111** [comment]
Just some feedback - its not going to be tied to the user. Its going to be the manner in which the data is filled in and what data is present.

**Comment by NBOVE1** [comment]
Met with User to continue troubleshooting issue. User was attempting to enter data for multiple measures in MONITORING. User was not utilizing the dropdown in Measures Monitoring History. Team reviewed the user guide with user and completed entering data for one measure in Strategy C2. User then entered data for another measure on her own. User felt competent in using the IPA tracker moving forward.
