### ISSUE TITLE
Service Request by Jessica Neufeld about Strategy Re-activation option

### ISSUE THREAD

**Issue by dlounsbu** [dlounsbu/NYHEALing-IPAtracker-support#41]
- [x] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [x] Problem FULLY RESOLVED and Issue is Closed
- [x] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by dlounsbu** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link=blue vlink="#954F72" style='tab-interval:.5in'>


<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
mso-ascii-theme-font:minor-latin;mso-hansi-theme-font:minor-latin;mso-bidi-font-family:
"Times New Roman";mso-bidi-theme-font:minor-bidi;color:#1F497D'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
mso-ascii-theme-font:minor-latin;mso-hansi-theme-font:minor-latin;mso-bidi-font-family:
"Times New Roman";mso-bidi-theme-font:minor-bidi;color:#1F497D'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><b><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
mso-fareast-font-family:"Times New Roman"'>From:</span></b><span
style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
"Times New Roman"'> david lounsbury <br>
<b>Sent:</b> Tuesday, September 21, 2021 6:30 PM<br>
<b>To:</b> Jessica Neufeld &lt;jn2434@columbia.edu&gt;<br>
<b>Cc:</b> Sandra Rodriguez &lt;sr3717@columbia.edu&gt;; Donrie Purcell
&lt;donrie.purcell@einsteinmed.org&gt;; Nicholas Bove &lt;nicholas.bove@einsteinmed.org&gt;;
Emma Rodgers &lt;emr2241@columbia.edu&gt;<br>
<b>Subject:</b> RE: Strategy Discontinue button now available<o:p></o:p></span></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
color:#1F497D'>Hi Jessica:<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
color:#1F497D'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
color:#1F497D'>I see now! <o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
color:#1F497D'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
color:#1F497D'>So, we will add a re-active option. <o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
color:#1F497D'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
color:#1F497D'>That should be straightforward to fix.<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
color:#1F497D'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
color:#1F497D'>Best,<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
color:#1F497D'>David<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
color:#1F497D'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
color:#1F497D'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
color:#1F497D'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
color:#1F497D'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
color:#1F497D'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal style='mso-outline-level:1'><b><span style='font-size:11.0pt;
font-family:"Calibri",sans-serif'>From:</span></b><span style='font-size:11.0pt;
font-family:"Calibri",sans-serif'> Jessica Neufeld [<a
href="mailto:jn2434@columbia.edu">mailto:jn2434@columbia.edu</a>] <br>
<b>Sent:</b> Tuesday, September 21, 2021 5:23 PM<br>
<b>To:</b> david lounsbury &lt;<a href="mailto:david.lounsbury@einsteinmed.org">david.lounsbury@einsteinmed.org</a>&gt;<br>
<b>Cc:</b> Sandra Rodriguez &lt;<a href="mailto:sr3717@columbia.edu">sr3717@columbia.edu</a>&gt;;
Donrie Purcell &lt;<a href="mailto:donrie.purcell@einsteinmed.org">donrie.purcell@einsteinmed.org</a>&gt;;
Nicholas Bove &lt;<a href="mailto:nicholas.bove@einsteinmed.org">nicholas.bove@einsteinmed.org</a>&gt;;
Emma Rodgers &lt;<a href="mailto:emr2241@columbia.edu">emr2241@columbia.edu</a>&gt;<br>
<b>Subject:</b> Re: Strategy Discontinue button now available<o:p></o:p></span></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>



CAUTION: This email comes from an external source; the   attachments and/or links may compromise our secure environment. Do not open   or click on suspicious emails. Please click on the “Phish Alert” button on   the top right of the Outlook dashboard to report any suspicious emails.
--




<p class=MsoNormal>Hi David,&nbsp; <o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>Not delete, but mislabels/ selects discontinued and then
wants to change the strategy back to active. Is there a way to reactivate it
from the discontinued button?&nbsp;<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>thanks,<o:p></o:p></p>

<p class=MsoNormal>Jessica<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>On Tue, Sep 21, 2021 at 4:27 PM david lounsbury &lt;<a
href="mailto:david.lounsbury@einsteinmed.org">david.lounsbury@einsteinmed.org</a>&gt;
wrote:<o:p></o:p></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='font-size:11.0pt;font-family:"Calibri",sans-serif;color:#1F497D'>Hi
(again) Jessica:</span><o:p></o:p></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='font-size:11.0pt;font-family:"Calibri",sans-serif;color:#1F497D'>&nbsp;</span><o:p></o:p></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='font-size:11.0pt;font-family:"Calibri",sans-serif;color:#1F497D'>Now, if
they actually deleted the IPA/Strategy, then the data would be removed from
view and would not be downloaded via Data Download. However, even in the case
that the IPA/Strategy was actually deleted, my understanding is that you can
download ‘history’ and find the old information. </span><o:p></o:p></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='font-size:11.0pt;font-family:"Calibri",sans-serif;color:#1F497D'>&nbsp;</span><o:p></o:p></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='font-size:11.0pt;font-family:"Calibri",sans-serif;color:#1F497D'>Let me
know if this helps and if you need something, just send us a Service Request! </span><o:p></o:p></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='font-size:11.0pt;font-family:"Calibri",sans-serif;color:#1F497D'>&nbsp;</span><o:p></o:p></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='font-size:11.0pt;font-family:"Calibri",sans-serif;color:#1F497D'><a
href="https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdlounsbu%2FNYHEALing-IPAtracker-support&amp;data=04%7C01%7Cdavid.lounsbury%40einsteinmed.org%7C59c6a2f1ec604af1dd0408d97d460a1c%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637678562058035434%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=s77hdF3zfjPhlePl4YjJrQE82wJmYqP1QohqiA6ipXU%3D&amp;reserved=0"
target="_blank">https://github.com/dlounsbu/NYHEALing-IPAtracker-support</a></span><o:p></o:p></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span
style='font-size:11.0pt;font-family:"Calibri",sans-serif;color:#1F497D'><br>
DL</span><o:p></o:p></p>


</body>

</html>

**Comment by dlounsbu** [comment]
Hi @jbazinet1111 

Please add an option to allow a user to 'Reactivate' a 'Discontinued' Strategy. 

Thanks,
David

**Comment by dlounsbu** [comment]
Hi Jeff: 

Let me know if you can do this for us. What would your professional time be, to add this feature?

DL

**Comment by jbazinet1111** [comment]
I'd be hesitant to put this upload feature into the application as it can be very involved. The upload portion itself isn't that bad but the data validation would be extensive and then you have to handle partial uploads, error resolution, etc. I would be happy to assist with uploading data behind the scenes on an ad-hoc basis but even with that, the time involved really depends upon the layout of the file and how it matches up to our schema.

**Comment by jbazinet1111** [comment]
Ha! Sorry. I was referring to a different issue!

For a reactivation button...2 hours. Not a big deal.

**Comment by dlounsbu** [comment]
> Ha! Sorry. I was referring to a different issue!
> 
> For a reactivation button...2 hours. Not a big deal.

Thanks! and APPROVED

DL

**Comment by jbazinet1111** [comment]
This has been deployed

**Comment by dlounsbu** [comment]
> This has been deployed

Excellent
