### ISSUE TITLE
Service Request by Nick Bove for Katy about Measures

### ISSUE THREAD

**Issue by NBOVE1** [dlounsbu/NYHEALing-IPAtracker-support#46]
- [ ] Qualtrics Service Request Form was received from User
- [x] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by NBOVE1** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/NBOVE/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/NBOVE/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/NBOVE/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link="#0563C1" vlink="#954F72" style='tab-interval:.5in'>


<p class=MsoNormal><span style='font-size:11.0pt;mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;mso-hansi-font-family:Calibri;mso-hansi-theme-font:
minor-latin;mso-bidi-font-family:"Times New Roman";mso-bidi-theme-font:minor-bidi;
color:#1F497D'>Hi Katy,<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;mso-hansi-font-family:Calibri;mso-hansi-theme-font:
minor-latin;mso-bidi-font-family:"Times New Roman";mso-bidi-theme-font:minor-bidi;
color:#1F497D'>Thanks for reaching out. I’m including Donrie and Jessica to
help provide further guidance. I’ve responded with my thoughts below. Also
please feel free to use our github account to keep our team in the loop with
any issues/updates to the IPA Tracker<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;mso-hansi-font-family:Calibri;mso-hansi-theme-font:
minor-latin;mso-bidi-font-family:"Times New Roman";mso-bidi-theme-font:minor-bidi;
color:#1F497D'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;mso-hansi-font-family:Calibri;mso-hansi-theme-font:
minor-latin;mso-bidi-font-family:"Times New Roman";mso-bidi-theme-font:minor-bidi;
color:#1F497D'><a
href="https://einsteinmed.co1.qualtrics.com/jfe/form/SV_4TvKdfrpwnbgBrE">https://einsteinmed.co1.qualtrics.com/jfe/form/SV_4TvKdfrpwnbgBrE</a>
:<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;mso-hansi-font-family:Calibri;mso-hansi-theme-font:
minor-latin;mso-bidi-font-family:"Times New Roman";mso-bidi-theme-font:minor-bidi;
color:#1F497D'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><b><span style='font-size:11.0pt;mso-fareast-font-family:
"Times New Roman"'>From:</span></b><span style='font-size:11.0pt;mso-fareast-font-family:
"Times New Roman"'> datapcputnam@gmail.com [mailto:datapcputnam@gmail.com] <br>
<b>Sent:</b> Tuesday, September 28, 2021 11:54 AM<br>
<b>To:</b> Nicholas Bove &lt;nicholas.bove@einsteinmed.org&gt;<br>
<b>Cc:</b> n.malgarinos@sascorp.org; info@preventioncouncilputnam.org;
ljohnson@preventioncouncilputnam.org<br>
<b>Subject:</b> IPA Tracker Questions<o:p></o:p></span></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>



CAUTION: This email comes from an external source; the   attachments and/or links may compromise our secure environment. Do not open   or click on suspicious emails. Please click on the “Phish Alert” button on   the top right of the Outlook dashboard to report any suspicious emails.
--




<p class=MsoNormal><span style='font-size:11.0pt'>Nick,<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt'>We have some questions
regarding the IPA Tracker for Putnam.<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt'>Under OEND regarding A1 and
B2, we believe this should be changed from doses to kits?&nbsp; Since there are
two doses in each kit, we will have to double the numbers if we use doses.<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;mso-hansi-font-family:Calibri;mso-hansi-theme-font:
minor-latin;mso-bidi-font-family:"Times New Roman";mso-bidi-theme-font:minor-bidi'><o:p>&nbsp;</o:p></span></p>

<p class=Default><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
mso-ascii-theme-font:minor-latin;mso-hansi-theme-font:minor-latin;mso-bidi-font-family:
"Times New Roman";mso-bidi-theme-font:minor-bidi;color:windowtext;background:
yellow;mso-highlight:yellow'>The correct language should be “# of naloxone
units distributed in communities”. I’ll update the language in the dropdown for
primary measures.</span><span style='font-size:9.0pt;color:windowtext'><o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt'>A5 is under MOUD and it
should be under OEND.&nbsp; However, it is also redundant to A1 and the numbers
will be duplicate if reported under both?<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;mso-hansi-font-family:Calibri;mso-hansi-theme-font:
minor-latin;mso-bidi-font-family:"Times New Roman";mso-bidi-theme-font:minor-bidi;
color:#1F497D'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;mso-hansi-font-family:Calibri;mso-hansi-theme-font:
minor-latin;mso-bidi-font-family:"Times New Roman";mso-bidi-theme-font:minor-bidi;
background:yellow;mso-highlight:yellow'>I’ve moved A5 to OEND. Although the
strategies are similar, data would have to be reported under both strategies.</span><span
style='font-size:11.0pt;mso-ascii-font-family:Calibri;mso-ascii-theme-font:
minor-latin;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin;
mso-bidi-font-family:"Times New Roman";mso-bidi-theme-font:minor-bidi'><o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt'>F1 - number of non-fatal
opioid overdose events. &nbsp; We already report this every month, should we
report it here again?&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;background:yellow;mso-highlight:
yellow'>Yes, please report it here as a measure for F1 on a monthly basis.</span><span
style='font-size:11.0pt'><o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt'>Can you please clarify if
“3.7 Number of community-based opioid overdose prevention education and
naloxone distribution (OEND) programs” refers to an organization that is a NY
OOPP or refers to an OEND training event?&nbsp;&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;background:yellow;mso-highlight:
yellow'>Jessica, can you please clarify how this measure is defined?</span><span
style='font-size:11.0pt'><o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt'>Thank you,<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt'><br>
Katy <o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-size:10.0pt;font-family:"Arial",sans-serif;
color:black;background:white'>Katherine J. Roberts, Ed.D., M.P.H., MCHES, CPH</span><span
style='font-size:10.0pt;font-family:"Times New Roman",serif'><o:p></o:p></span></p>

<p class=MsoNormal style='background:white'><span style='font-size:10.0pt;
font-family:"Arial",sans-serif;color:black'>Data Coordinator&nbsp;</span><span
style='font-size:10.0pt;font-family:"Arial",sans-serif;color:#202124'><o:p></o:p></span></p>

<p class=MsoNormal style='background:white'><span style='font-size:10.0pt;
font-family:"Arial",sans-serif;color:black'>Putnam HEALing Communities Study</span><span
style='font-size:10.0pt;font-family:"Arial",sans-serif;color:#202124'><o:p></o:p></span></p>

<p class=MsoNormal style='background:white'><span style='font-size:10.0pt;
font-family:"Arial",sans-serif;color:black'>917-817-0785</span><span
style='font-size:10.0pt;font-family:"Arial",sans-serif;color:#202124'><o:p></o:p></span></p>


</body>

</html>

**Comment by dlounsbu** [comment]
@donriepurcell we need to rapidly and proactively provide feedback to each county to address questions like these. All measures need proper units. And there shouldn’t be any measures that is not MONITORABLE, so to speak.

**Comment by NBOVE1** [comment]
Hi Nick,

Thanks for getting back to us. I have a couple of follow up comments/concerns please see below.
I’ve moved A5 to OEND. Although the strategies are similar, data would have to be reported under both strategies. 
-     This is confusing to us – if we report in both places we would be double reporting the number of naloxone units distributed in Putnam. Can you explain the rational for this? 

Sure, not a problem. The IPA Tracker is built to be IPA specific. The data collected are generated into reports that can only be reported at the IPA level. The tracker doesn’t read across IPA’s and loop data together if the measure is similar. This was created in this way in order for counties to be able to report on measures that might be worded the same but might differ from partner to partner. In strategies A1 vs A5, they both have very similar measures but will need to be reported separately to align with the way the tracker was built. I hope this is helpful! 
Best,
Nick
