### ISSUE TITLE
Service Request by [DONRIE PURCELL] related to a bug in the measures download 

### ISSUE THREAD

**Issue by donriepurcell** [dlounsbu/NYHEALing-IPAtracker-support#50]
- [ ] Qualtrics Service Request Form was received from User
- [ ] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by donriepurcell** [comment]
Hi Jeff 
I am doing some reconciliation with two tables using the strategies download and the measures download. I have noticed that there is a **B1** code/**strategy code**  attached the Putnam County in the download  which is not consistent wit what is actually in Putnam county. 
Please  can you take a look at it, and let me know if and why there may be a reason for the discrepancy. 
Regards
Donrie 
<img width="1653" alt="Screen Shot 2021-09-30 at 4 30 26 PM" src="https://user-images.githubusercontent.com/80912517/135526822-02d9c7f1-e39a-4e80-a055-df32753918cd.png">

**Comment by jbazinet1111** [comment]
Not sure, Donrie. I cannot duplicate this issue and there isn't a B1 strategy in the database for this county/ipa. The download I just ran did not have this errant strategy included.

**Comment by donriepurcell** [comment]
OK, that's great !

**Comment by donriepurcell** [comment]
I am going ti re-run the entire data sheet because  I ran into another issue  with the download relating to **issue # 47** 
Jeff I am going to add the screen shots here and in issue # 47 so they are placed in the correct spots 


![Screen Shot 2021-10-01 at 10 15 10 AM](https://user-images.githubusercontent.com/80912517/135635708-08764fcc-1e69-401d-bb10-59bf9cba6588.png)
<img width="1276" alt="Screen Shot 2021-10-01 at 10 14 05 AM" src="https://user-images.githubusercontent.com/80912517/135635718-c3fa6d66-4558-4cdf-89ac-22433a048824.png">

**Comment by jbazinet1111** [comment]
Can this issue be closed?

**Comment by dlounsbu** [comment]
Yes! Thanks Jeff!
