### ISSUE TITLE
Service Request by Mia Christopher on missing display of option selections in SECTORS and PRIORITY POPS in Smart Strategy Measures Form

### ISSUE THREAD

**Issue by donriepurcell** [dlounsbu/NYHEALing-IPAtracker-support#53]
- [x] Qualtrics Service Request Form was received from User
- [x] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [x] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by donriepurcell** [comment]
Hi Jeff 
The Research Coordinators have noted that data in the fields for high risk populations etc have all but disappeared.
![example 3 47](https://user-images.githubusercontent.com/80912517/136268613-9cef1b93-2fda-4786-a862-0c5eb5fb16ad.jpg)
![example 1 27](https://user-images.githubusercontent.com/80912517/136268648-5f4f9044-5573-4e92-b1c2-c7e7557905e2.jpg)
![example 2 74](https://user-images.githubusercontent.com/80912517/136268689-fa70f9cc-58af-437c-9d9a-2eba3e57c69a.jpg)

**Comment by donriepurcell** [comment]
Jeff please follow this email trail:

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40"><p class="MsoNormal" style="margin: 0in 0in 12pt; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><a name="_MailOriginal"><b><span style="font-size: 12pt; color: black;">From:<span class="Apple-converted-space"> </span></span></b></a><span><span style="font-size: 12pt; color: black;">Mia Christopher &lt;mm5651@columbia.edu&gt;<br><b>Date:<span class="Apple-converted-space"> </span></b>Wednesday, October 6, 2021 at 3:01 PM<br><b>To:<span class="Apple-converted-space"> </span></b>Donrie Purcell &lt;donrie.purcell@einsteinmed.org&gt;<br><b>Cc:<span class="Apple-converted-space"> </span></b>Nicholas Bove &lt;nicholas.bove@einsteinmed.org&gt;, david lounsbury &lt;david.lounsbury@einsteinmed.org&gt;<br><b>Subject:<span class="Apple-converted-space"> </span></b>Re: Screen shot!<o:p></o:p></span></span></p><span style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"></span>

CAUTION: This email comes from an external source; the attachments and/or links may compromise our secure environment. Do not open or click on suspicious emails. Please click on the “Phish Alert” button on the top right of the Outlook dashboard to report any suspicious emails.
--


<p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><span>Hi Donrie,<o:p></o:p></span></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><span><o:p> </o:p></span></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><span>Attached are screenshots from three different counties showing that the priority sectors, high risk pop, additional pop, and medications included are blank. I have found this is the case for every IPA I have looked at.<span class="Apple-converted-space"> </span><o:p></o:p></span></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><span><o:p> </o:p></span></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><span>Thank you,<o:p></o:p></span></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><span>Mia<o:p></o:p></span></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><span><o:p> </o:p></span></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><span>On Wed, Oct 6, 2021 at 2:53 PM Donrie Purcell &lt;</span></span><a href="mailto:donrie.purcell@einsteinmed.org" style="color: rgb(149, 79, 114); text-decoration: underline;"><span><span>donrie.purcell@einsteinmed.org</span></span><span></span></a><span><span>&gt; wrote:<o:p></o:p></span></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;">Hi Mia<span class="Apple-converted-space"> </span></span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"> </span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;">Please send me a screen shot so I can work with the vendor immediately on this.<span class="Apple-converted-space"> </span></span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"> </span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; vertical-align: baseline;"><span><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif; color: black;">Regards<br>Donrie Purcell, PhD, MPH</span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; vertical-align: baseline;"><span><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif; color: black;"> </span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; vertical-align: baseline;"><span><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif; color: black;">Every generation has the obligation to free men's minds for a look at new worlds,....to look out from a higher plateau than the last generation.<br>Ellison S. Onizuka <br><br><br>CONFIDENTIALITY: This email (including any attachments) may contain confidential, proprietary and/or privileged information. Any duplication, copying, distribution, dissemination, transmission, disclosure or use in any manner of this email (including any attachments) without the authorization of the sender is strictly prohibited. If you receive this email (including any attachments) in error, please notify the sender and delete this email (including any attachments) from your system. Thank you.</span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"> </span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"> </span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"> </span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><span><br clear="all"><o:p></o:p></span></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><span><o:p> </o:p></span></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><span>--<span class="Apple-converted-space"> </span><o:p></o:p></span></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><b><span>Mia Christopher, MPH</span></b></span><span><span><o:p></o:p></span></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><i><span>(she/her)</span></i></span><span><span><o:p></o:p></span></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><span>Regional Research Coordinator<o:p></o:p></span></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><span>Social Intervention Group<o:p></o:p></span></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><span>HEALing Communities Study<o:p></o:p></span></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><span>Columbia University School of Social Work<o:p></o:p></span></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><span>Email:<span class="Apple-converted-space"> </span></span></span><a href="mailto:mm5651@columbia.edu" target="_blank" style="color: rgb(149, 79, 114); text-decoration: underline;"><span><span>mm5651@columbia.edu</span></span><span></span></a><span><span><o:p></o:p></span></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><span>Phone: (646) 532- 7331<o:p></o:p></span></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span></span><a href="https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsig.columbia.edu%2F&amp;data=04%7C01%7Cdonrie.purcell%40einsteinmed.org%7C1da8b038014b487d1ac508d988fbb354%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637691436904291534%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=emDtePzHH%2BTQitbLmiX9tU9Eg5kMTnZia5XAVtGADKg%3D&amp;reserved=0" target="_blank" style="color: rgb(149, 79, 114); text-decoration: underline;"><span><span style="font-family: Verdana, sans-serif; color: rgb(17, 85, 204);">https://sig.columbia.edu/<br></span></span><span></span></a><span><span><o:p></o:p></span></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span></span><a href="https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsig.columbia.edu%2F&amp;data=04%7C01%7Cdonrie.purcell%40einsteinmed.org%7C1da8b038014b487d1ac508d988fbb354%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637691436904301525%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=hZrLNB2pqkzt5nxCHk2NmysuqAt4TtAVsQGdSNtkHh0%3D&amp;reserved=0" target="_blank" style="color: rgb(149, 79, 114); text-decoration: underline;"><span><span style="font-family: Verdana, sans-serif; color: rgb(17, 85, 204);"><br></span></span><span></span></a><span><span><o:p></o:p></span></span></p><p class="MsoNormal" style="margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span><b><i><span>We at CSSW condemn anti-Black racism in all its forms and are committed not just to making statements, but to taking action.</span></i></b></span><span></span><span><o:p></o:p></span></p></html>

**Comment by dlounsbu** [comment]
@donriepurcell 

I see the issue. Any data options (labels) seem to be missing from the Tracker form. 

DL

**Comment by dlounsbu** [comment]
Sector and Priority Pop data are downloading, I see, but not showing in the on-line IPA Tracker form. 

Interesting.

**Comment by dlounsbu** [comment]
From: Donrie Purcell 
Sent: Wednesday, October 6, 2021 3:23 PM
To: david lounsbury <david.lounsbury@einsteinmed.org>
Cc: Nicholas Bove <nicholas.bove@einsteinmed.org>
Subject: Re: Screen shot!

Hi Profe’

I am including Nick on the email  (team work and transparency).
I believe the change I requested for the download has created the mess we are seeing in the countries now. 

Regards
Donrie 

From: david lounsbury <david.lounsbury@einsteinmed.org>
Date: Wednesday, October 6, 2021 at 3:10 PM
To: Donrie Purcell <donrie.purcell@einsteinmed.org>
Subject: RE: Screen shot!
Hi Donrie:

Did Jeff change anything about how the Sector Fields are set up in the Tracker?? 

Maybe this change cannot be implemented now. 

Or is there something else going on with the Tracker??
DL

**Comment by dlounsbu** [comment]
From: david lounsbury 
Sent: Wednesday, October 6, 2021 4:06 PM
To: Donrie Purcell <donrie.purcell@einsteinmed.org>
Cc: Nicholas Bove <nicholas.bove@einsteinmed.org>
Subject: RE: Screen shot!

Hi Donrie:

I was concerned about that. No worries, but we need to have Jeff uninstall that change. I think we can re-implement this as we step into Wave 2. 

DL

**Comment by jbazinet1111** [comment]
I need to know which counties and strategies. I only knew of Greene county/A2 and I deduced that from the screenshot.


________________________________
