### ISSUE TITLE
Service Request by Megan Donato 

### ISSUE THREAD

**Issue by donriepurcell** [dlounsbu/NYHEALing-IPAtracker-support#54]
- [ ] Qualtrics Service Request Form was received from User
- [ ] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by donriepurcell** [comment]
Hi Jeff 
We have to document every request for internal data analytic purposes.
This was not done to poke the bear. 
In fact, I BCC'd you on the email to Megan alerting her that you've begun working on this already. 
Given that Megan filled out a Qualtrics Service Request Form. I am obliged to create the service request.
My actions are all about documentation, accountability, and creating a paper trail,...

**Comment by jbazinet1111** [comment]
Ok. Thanks. Let’s skip assigning the issue to me if it is a duplicate.
