### ISSUE TITLE
Service Request by Anna  Weiskopf about Missing CID data in the Tracker

### ISSUE THREAD

**Issue by dlounsbu** [dlounsbu/NYHEALing-IPAtracker-support#57]
- [x] Qualtrics Service Request Form was received from User
- [x] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by dlounsbu** [comment]
Hi Donrie:

Per our discussion, it looks like this is not a bug. 

Send Anna a copy of the DUI of current IPA/Strategy Specification information and point out how she can use it to organize herself to enter the missing CID data, quickly, into the Tracker!

THANK YOU

**Comment by dlounsbu** [comment]
@donriepurcell and @NBOVE1 

Please follow up with Anna. Is this matter resolved?

**Comment by NBOVE1** [comment]
@dlounsbu Good Morning David. I've just checked several strategies in different counties and ran a report and CID are generating perfectly fine. I'm closing this issue and will connect with Anna to let her know:
![image](https://user-images.githubusercontent.com/88558561/140516885-28fe16d6-d7f8-4762-a146-d101852e0966.png)
