### ISSUE TITLE
Service Request by DONRIE PURCELL to allow administrative access that are Isolated to One  or more counties 

### ISSUE THREAD

**Issue by donriepurcell** [dlounsbu/NYHEALing-IPAtracker-support#58]
- [ ] Qualtrics Service Request Form was received from User
- [ ] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by jbazinet1111** [comment]
We're looking at 10 hours, David. This hits just about every component of the site but its not too intrusive.

**Comment by jbazinet1111** [comment]
The OTHER MEASURES list item is there in List Options. I had added it to the very bottom, grouped with the other measure types.
