### ISSUE TITLE
Service Request by Emila Camp in Suffolk about Demo and Med data parsing

### ISSUE THREAD

**Issue by dlounsbu** [dlounsbu/NYHEALing-IPAtracker-support#61]
- [x] Qualtrics Service Request Form was received from User
- [x] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by NBOVE1** [comment]
Hi Everyone,
I wanted to circle back to this bug. @jbazinet1111 It appears as if when entering demographics, users continue to get A)Female self generated in the textbox for Female, :: for NR (Gender), and : for NR (Age Group). Did you have a chance to take a look at this further? Thanks! Nick

![image](https://user-images.githubusercontent.com/88558561/140191361-b17dfeb6-f991-4f93-b04d-b9f964211ac7.png)

**Comment by dlounsbu** [comment]
Hi Nick:

I have observed this in the Tracker Downloads, too. 

[DUI 2021-10-28 ALL COMMUNITIES formulas .xlsx](https://github.com/dlounsbu/NYHEALing-IPAtracker-support/files/7470644/DUI.2021-10-28.ALL.COMMUNITIES.formulas.xlsx)

See Measures in the this file, and filter by demo variables. There may be a similar problem for Medication type.

Also, Jeff, I am not sure how to easily parse the data in the demo fields, so that we can analyze it. 

DL

**Comment by dlounsbu** [comment]
@jbazinet1111 Just touching on this again. How data is being stored for demographic summary info and medication info is the issue. I realize that the system is storing the data as a string of information, not individual data elements. Am I correct? We may need to restructure how data is stored. Thoughts?

**Comment by NBOVE1** [comment]
This issue has been resolved. I've checked Suffolk's demographics and attempted to add new demographics in practiceCO. All worked properly. I'll reach out to Emilia and team to let them know:

![image](https://user-images.githubusercontent.com/88558561/141369094-e22ceb80-004f-4ea3-9421-3d7046f72411.png)
