### ISSUE TITLE
Service Request by [Donrie Purcell] on data download & possible displacement of fields

### ISSUE THREAD

**Issue by donriepurcell** [dlounsbu/NYHEALing-IPAtracker-support#63]
- [ ] Qualtrics Service Request Form was received from User
- [ ] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by donriepurcell** [comment]
In the first instance,  I am running this issue by David and Nick for possible feedback'
I don't quite know yet if this is because of the data download or the way the data is pulled into SPSS  causing data displacement. Here goes; 

I started isolating each county in SPSS and running separate tables, I noticed that a number of the measures were not in sync with the EPB's see screen shot 1.  
An example is: IPA: MOUD Expansion B1    Strategy: B1-Disc. CHAD.

![Screen Shot 2021-11-02 at 1 01 53 PM](https://user-images.githubusercontent.com/80912517/139913350-26cbf668-8b16-4e3b-bcb5-b54ce029bf81.png)

I decided to investigate further by going to the IPA tracker and pouring through the data. 
It is very clear that the above mentioned IPA was appropriately entered and under the **EPB** of **Expand MOUD Availability**. 

![Screen Shot 2021-11-02 at 1 16 56 PM](https://user-images.githubusercontent.com/80912517/139915654-17e8e738-b825-49ef-b503-b643c67c1083.png)

This now begs the question why is it being displaced in SPSS,.....?

**Comment by donriepurcell** [comment]
Profe' 
when I run it by itself as a measure this is what I am getting
![Screen Shot 2021-11-02 at 1 49 25 PM](https://user-images.githubusercontent.com/80912517/139919060-4c4df963-bce0-4e9f-84d8-efc2bc49874d.png)

**Comment by dlounsbu** [comment]
Hi Donrie:

Seems like it may have to do with the SPSS data merge??

Maybe? 

I would need to review the data file with you. 

DL

**Comment by donriepurcell** [comment]
yes yes

**Comment by donriepurcell** [comment]
thanks

**Comment by dlounsbu** [comment]
I can meet from 3:30 to 4pm. If you want. Send me a zoom link or call then!

**Comment by donriepurcell** [comment]
I will send the zoom link

**Comment by donriepurcell** [comment]
and continue looking because the EPB Field itself could be a distortion

**Comment by donriepurcell** [comment]
I think I found the reason, I am hopeful you will confirm when we see

**Comment by dlounsbu** [comment]
@donriepurcell What are you suggesting be done? The records that have been 'Deactivated' are the ones without an 'EBP' category, and that is appropriate. You code missing to 'Deactivated', or something, in your SPSS data table.

**Comment by donriepurcell** [comment]
this item has been resolved by us both. I am closing this. At best we understand the discontinued strategies are the issue
