### ISSUE TITLE
Service Request by Veronica Salvas

### ISSUE THREAD

**Issue by NBOVE1** [dlounsbu/NYHEALing-IPAtracker-support#66]
- [ ] Qualtrics Service Request Form was received from User
- [ ] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by NBOVE1** [comment]
Veronica Salvas had requested support around a technical issue scrolling downward on listed IPA's. Donrie and I met with Veronica on 11/11/21 to troubleshoot issue. Issue was resolved by updating settings on her MacBook. Veronica was using Safari and needed to update settings to properly allow her to scroll.

**Comment by dlounsbu** [comment]
Interesting. And good work. Please make a note of it for other users!

**Comment by NBOVE1** [comment]
Sure, will do!
