### ISSUE TITLE
Service Request by [Mia Christopher]on inability in seeing Monitoring data

### ISSUE THREAD

**Issue by donriepurcell** [dlounsbu/NYHEALing-IPAtracker-support#68]
- [ ] Qualtrics Service Request Form was received from User
- [ ] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by donriepurcell** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40"><p class="MsoNormal" style="margin: 0in 0in 12pt; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><b><span style="font-size: 12pt; color: black;">From:<span class="Apple-converted-space"> </span></span></b><span style="font-size: 12pt; color: black;">Donrie Purcell &lt;donrie.purcell@einsteinmed.org&gt;<br><b>Date:<span class="Apple-converted-space"> </span></b>Monday, November 22, 2021 at 4:25 PM<br><b>To:<span class="Apple-converted-space"> </span></b>Mia Christopher &lt;mm5651@columbia.edu&gt;<br><b>Cc:<span class="Apple-converted-space"> </span></b>david lounsbury &lt;david.lounsbury@einsteinmed.org&gt;<br><b>Subject:<span class="Apple-converted-space"> </span></b>Re: IPA tracker<o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;">Hi Mia<span class="Apple-converted-space"> </span><u1:p></u1:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"><u1:p> </u1:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;">I am seeing it. If you wish, you and I can do a quick zoom.<u1:p></u1:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;">You just have to tell me when and I am there.<u1:p></u1:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; vertical-align: baseline;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif; color: black;">Regards<br>Donrie Purcell, PhD, MPH<u1:p></u1:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; vertical-align: baseline;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif; color: black;"><u1:p> </u1:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; vertical-align: baseline;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif; color: black;">Every generation has the obligation to free men's minds for a look at new worlds,....to look out from a higher plateau than the last generation.<br>Ellison S. Onizuka <br><br><br>CONFIDENTIALITY: This email (including any attachments) may contain confidential, proprietary and/or privileged information. Any duplication, copying, distribution, dissemination, transmission, disclosure or use in any manner of this email (including any attachments) without the authorization of the sender is strictly prohibited. If you receive this email (including any attachments) in error, please notify the sender and delete this email (including any attachments) from your system. Thank you.<u1:p></u1:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"><u1:p> </u1:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"><u1:p> </u1:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"><u1:p> </u1:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"><u1:p> </u1:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in 0in 12pt; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><b><span style="font-size: 12pt; color: black;">From:<span class="Apple-converted-space"> </span></span></b><span style="font-size: 12pt; color: black;">Mia Christopher &lt;mm5651@columbia.edu&gt;<br><b>Date:<span class="Apple-converted-space"> </span></b>Monday, November 22, 2021 at 4:18 PM<br><b>To:<span class="Apple-converted-space"> </span></b>Donrie Purcell &lt;donrie.purcell@einsteinmed.org&gt;<br><b>Subject:<span class="Apple-converted-space"> </span></b>IPA tracker<u1:p></u1:p></span><span><o:p></o:p></span></p>

CAUTION: This email comes from an external source; the attachments and/or links may compromise our secure environment. Do not open or click on suspicious emails. Please click on the “Phish Alert” button on the top right of the Outlook dashboard to report any suspicious emails.
--


<p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt; color: white;">Hi Donrie,<span class="Apple-converted-space"> </span></span><span><u1:p></u1:p><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;"><u1:p> </u1:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;">The "number of referrals from peer" is not showing up from this page (strategy 2A2). See attached. But it does show up in the drop down menu on the same page. Do you know why this might be?<u1:p></u1:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;"><u1:p> </u1:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;">Thanks,<u1:p></u1:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;">Mia<br clear="all"></span><span><u1:p></u1:p><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;"><u1:p> </u1:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;">--<span class="Apple-converted-space"> </span><u1:p></u1:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><b><span style="font-size: 11pt;">Mia Christopher, MPH</span></b><span><u1:p></u1:p><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><i><span style="font-size: 11pt;">(she/her)</span></i><span><u1:p></u1:p><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;">Regional Research Coordinator<u1:p></u1:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;">Social Intervention Group<u1:p></u1:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;">HEALing Communities Study<u1:p></u1:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;">Columbia University School of Social Work<u1:p></u1:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;">Email:<span class="Apple-converted-space"> </span><a href="mailto:mm5651@columbia.edu" target="_blank" style="color: rgb(149, 79, 114); text-decoration: underline;">mm5651@columbia.edu</a><u1:p></u1:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;">Phone: (646) 532- 7331<u1:p></u1:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;"><a href="https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsig.columbia.edu%2F&amp;data=04%7C01%7Cdonrie.purcell%40einsteinmed.org%7Ce508e8cf4b994624a02308d9adfda806%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637732127230553369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&amp;sdata=xUceDrDNBs8yPPJKOYTHdJorQWsYvZ2G9ZrPNp4lHts%3D&amp;reserved=0" target="_blank" style="color: rgb(149, 79, 114); text-decoration: underline;"><span style="font-family: Verdana, sans-serif; color: rgb(17, 85, 204);">https://sig.columbia.edu/<br></span></a></span><span><u1:p></u1:p><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;"><a href="https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsig.columbia.edu%2F&amp;data=04%7C01%7Cdonrie.purcell%40einsteinmed.org%7Ce508e8cf4b994624a02308d9adfda806%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637732127230563361%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&amp;sdata=OZ9CvOWAAigS%2Bl5MC%2FOxPtg0V8fcP6hSerAhEzthmWA%3D&amp;reserved=0" target="_blank" style="color: rgb(149, 79, 114); text-decoration: underline;"><span style="font-family: Verdana, sans-serif; color: rgb(17, 85, 204);"><br></span></a></span><span><u1:p></u1:p><o:p></o:p></span></p><b style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><i><span style="font-size: 11pt; font-family: Calibri, sans-serif;">We at CSSW condemn anti-B</span></i></b><span style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: -webkit-standard; font-size: medium; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; display: inline !important; float: none;"></span></html>

**Comment by donriepurcell** [comment]
<img width="198" alt="Screen Shot 2021-11-23 at 1 12 41 PM" src="https://user-images.githubusercontent.com/80912517/143080918-d10a50c4-6c06-4c37-87a7-bf0e75920ff0.png">

**Comment by NBOVE1** [comment]
Donrie has resolved issue with Mia.
