### ISSUE TITLE
Suffolk County reporting missing data in IPA Tracker

### ISSUE THREAD

**Issue by NBOVE1** [dlounsbu/NYHEALing-IPAtracker-support#69]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/NBOVE/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/NBOVE/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/NBOVE/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in'>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
mso-ascii-theme-font:minor-latin;mso-hansi-theme-font:minor-latin;mso-bidi-font-family:
"Times New Roman";mso-bidi-theme-font:minor-bidi;color:#1F497D'>Hi Dawn,<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
mso-ascii-theme-font:minor-latin;mso-hansi-theme-font:minor-latin;mso-bidi-font-family:
"Times New Roman";mso-bidi-theme-font:minor-bidi;color:#1F497D'>I feel we
should address this right away. Please propose several dates/times that Emilia
and you are available to meet with Donrie, me, and Jessica if she’s available.<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
mso-ascii-theme-font:minor-latin;mso-hansi-theme-font:minor-latin;mso-bidi-font-family:
"Times New Roman";mso-bidi-theme-font:minor-bidi;color:#1F497D'>Much
appreciated,<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
mso-ascii-theme-font:minor-latin;mso-hansi-theme-font:minor-latin;mso-bidi-font-family:
"Times New Roman";mso-bidi-theme-font:minor-bidi;color:#1F497D'>Nick<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
mso-ascii-theme-font:minor-latin;mso-hansi-theme-font:minor-latin;mso-bidi-font-family:
"Times New Roman";mso-bidi-theme-font:minor-bidi;color:#1F497D'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><b><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
mso-fareast-font-family:"Times New Roman"'>From:</span></b><span
style='font-size:11.0pt;font-family:"Calibri",sans-serif;mso-fareast-font-family:
"Times New Roman"'> Dawn E. Gruss [mailto:dg3207@columbia.edu] <br>
<b>Sent:</b> Thursday, December 9, 2021 12:46 PM<br>
<b>To:</b> Samantha W. Lang &lt;sl4732@columbia.edu&gt;; Jessica Neufeld
&lt;jn2434@columbia.edu&gt;; Nicholas Bove &lt;nicholas.bove@einsteinmed.edu&gt;<br>
<b>Cc:</b> Kristin Woodlock &lt;woodlockassociates@gmail.com&gt;; Blevins,
Derek (NYSPI) &lt;Derek.Blevins@nyspi.columbia.edu&gt;; Marotta, Alyse
&lt;Alyse.Marotta@suffolkcountyny.gov&gt;; Camp, Emilia
&lt;Emilia.Camp@suffolkcountyny.gov&gt;<br>
<b>Subject:</b> IPA Tracker Tool...<o:p></o:p></span></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

CAUTION: This   email comes from an external source; the attachments and/or links may   compromise our secure environment. Do not open or click on suspicious emails.   Please click on the “Phish Alert” button on the top right of the Outlook   dashboard to report any suspicious emails.
--

<p class=MsoNormal><span style='mso-fareast-font-family:"Times New Roman"'>Hello,
everyone!<o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-fareast-font-family:"Times New Roman"'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='mso-fareast-font-family:"Times New Roman"'>Alyse,
Emilia and I would like to revisit the discussion on the IPA tracker tool.
&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-fareast-font-family:"Times New Roman"'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='mso-fareast-font-family:"Times New Roman"'>In
working on the sustainability&nbsp;tool/plan, we used the IPA tracker tool to
support the discussion.&nbsp; Alyse and I noticed many of the IPAs still don't
reflect the work as it is occuring (as based on the last iteration of each IPA
that we drafted).<o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-fareast-font-family:"Times New Roman"'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='mso-fareast-font-family:"Times New Roman"'>And,
I believe, Emilia is still having some data entry/export issues. &nbsp;<o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-fareast-font-family:"Times New Roman"'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='mso-fareast-font-family:"Times New Roman"'>Before
we make any more changes to what is in the IPA Tracker - can we make this a top
agenda item to discuss during our coaching call next week?&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-fareast-font-family:"Times New Roman"'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='mso-fareast-font-family:"Times New Roman"'>If
you feel it needs to be sooner, please let us know.<o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-fareast-font-family:"Times New Roman"'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='mso-fareast-font-family:"Times New Roman"'>Thank
you!<o:p></o:p></span></p>

</body>

</html>

**Comment by dlounsbu** [comment]
Hi Nick:

Can you give me a call about this? 

DL

**Comment by dlounsbu** [comment]
> Hi Nick:
> 
> Can you give me a call about this?
> 
> DL

718 839-7452

**Comment by NBOVE1** [comment]
Met with team and issue resolved. Suffolk team has updated the IPA tracker to reflect their latest IPA's. Additionally, provided TA around downloading reports.
