### ISSUE TITLE
Service Request by [Jessica ] on county data view 

### ISSUE THREAD

**Issue by donriepurcell** [dlounsbu/NYHEALing-IPAtracker-support#70]
- [ ] Qualtrics Service Request Form was received from User
- [ ] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by dlounsbu** [comment]
Hi Donrie: 

Is this for Putnam only? 

DL

**Comment by donriepurcell** [comment]
Hi Jeff 
If possible can you please allow for the monitoring measures data to be downloaded and sorted according to the most recent date.

**Comment by donriepurcell** [comment]
No, all counties profe'

**Comment by dlounsbu** [comment]
> 

Hi Donrie: Monitoring would need to be sorted by IPA/Strategy, then by Measure, then by date for each point entered for a measure. At least that is what I would suggest. 

Is this getting at the matter? 

Downloaded data can be sorted in any way via Excel, of course.

**Comment by donriepurcell** [comment]
You don't understand, hold let me send the image

**Comment by donriepurcell** [comment]
Hi Jeff 
Can you sort this data as Jessica request for all the counties please. She wants the most recent data at the top.
