### ISSUE TITLE
Service Request by Katherine Roberts about MONITORING SMART Strategies

### ISSUE THREAD

**Issue by dlounsbu** [dlounsbu/NYHEALing-IPAtracker-support#71]
IPA SERVICE REQUEST SUMMARY

1. CONTACT INFORMATION:

Katherine  Roberts

Email:  datapcputnam@gmail.com

Phone:  917-817-0785

2. COUNTY

Putnam

3. WHICH FEATURE(S):

MONITORING: Creating, updated or deleting information about an implemented SMART Strategy

4. BRIEF PROBLEM DESCRIPTION:

I am unable to enter data in D1, under OEND. I click on "Show all measures" and D1 does not appear. 

5. URGENCY:

50

6. ANYTHING ELSE TO SHARE: 

- [x] Qualtrics Service Request Form was received from User
- [ ] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by dlounsbu** [comment]
Hi Donrie: 

Can you check this out for Putnam?? 

Thank you!
DL

**Comment by donriepurcell** [comment]
From: Donrie Purcell <donrie.purcell@einsteinmed.edu>
Date: Tuesday, December 14, 2021 at 10:35 AM
To: Campbell, Aimee C. <anc2002@cumc.columbia.edu>
Cc: moconnor@preventioncouncilputnam.org <moconnor@preventioncouncilputnam.org>, kristin0606@hotmail.com <kristin0606@hotmail.com>, info@preventioncouncilputnam.org <info@preventioncouncilputnam.org>, n.malgarinos@sascorp.org <n.malgarinos@sascorp.org>, roberts@interactivehlth.com <roberts@interactivehlth.com>, Erin Kim <ek3183@columbia.edu>, Nicholas Bove <nicholas.bove@einsteinmed.edu>, David Lounsbury <david.lounsbury@einsteinmed.edu>
Subject: D1 IPA monitoring data fix 
Good morning everyone
 
I do hope that I have included all the relevant parties. I wanted to let you know that you can now see and edit strategy D1 (OEND) in the Data Monitoring section of the IPA tracker.
I have included a pic for your review.
 
 
 
 
 
Regards
Donrie Purcell, PhD, MPH
 
Every generation has the obligation to free men's minds for a look at new worlds,....to look out from a higher plateau than the last generation.
Ellison S. Onizuka 


CONFIDENTIALITY: This email (including any attachments) may contain confidential, proprietary and/or privileged information. Any duplication, copying, distribution, dissemination, transmission, disclosure or use in any manner of this email (including any attachments) without the authorization of the sender is strictly prohibited. If you receive this email (including any attachments) in error, please notify the sender and delete this email (including any attachments) from your system. Thank you.
