### ISSUE TITLE
Service Request by [David Lounsbury] to review and modify ADMIN and COUNTY LEVEL access to the tracker 

### ISSUE THREAD

**Issue by donriepurcell** [dlounsbu/NYHEALing-IPAtracker-support#72]
- [ ] Qualtrics Service Request Form was received from User
- [ ] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by donriepurcell** [comment]
I will start by reviewing duplicates in the system. 
Then consult with Nick on who is who and why they may need a particular type of access in the system.

**Comment by dlounsbu** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=Edit-Time-Data
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_editdata.mso">

<link rel=themeData
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in'>


<p class=MsoNormal><span style='mso-ascii-font-family:Calibri;mso-ascii-theme-font:
minor-latin;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin;
mso-bidi-font-family:"Times New Roman";mso-bidi-theme-font:minor-bidi;
color:#1F497D'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='mso-ascii-font-family:Calibri;mso-ascii-theme-font:
minor-latin;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin;
mso-bidi-font-family:"Times New Roman";mso-bidi-theme-font:minor-bidi;
color:#1F497D'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><a name="_MailOriginal"><b><span style='mso-fareast-font-family:
"Times New Roman"'>From:</span></b></a><span style='mso-bookmark:_MailOriginal'><span
style='mso-fareast-font-family:"Times New Roman"'> Jeff Bazinet
[mailto:jbazinet@northcountryinitiative.org] <br>
<b>Sent:</b> Tuesday, December 14, 2021 10:05 AM<br>
<b>To:</b> David Lounsbury &lt;david.lounsbury@einsteinmed.edu&gt;; Nicholas
Bove &lt;nicholas.bove@einsteinmed.edu&gt;; Donrie Purcell
&lt;donrie.purcell@einsteinmed.edu&gt;<br>
<b>Subject:</b> Users/Wave<o:p></o:p></span></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'><o:p>&nbsp;</o:p></span></p>



CAUTION: This email comes from an external source; the   attachments and/or links may compromise our secure environment. Do not open   or click on suspicious emails. Please click on the “Phish Alert” button on   the top right of the Outlook dashboard to report any suspicious emails.
--




<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'>Just a reminder – <o:p></o:p></span></p>

<p class=MsoListParagraph style='text-indent:-.25in;mso-list:l0 level1 lfo1'><span
style='mso-bookmark:_MailOriginal'><![if !supportLists]><span style='font-family:
Symbol;mso-fareast-font-family:Symbol;mso-bidi-font-family:Symbol'><span
style='mso-list:Ignore'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><![endif]>All users, regardless of their Wave, are defined
in the Wave 1 database. <o:p></o:p></span></p>

<p class=MsoListParagraph style='margin-left:1.0in;text-indent:-.25in;
mso-list:l0 level2 lfo1'><span style='mso-bookmark:_MailOriginal'><![if !supportLists]><span
style='font-family:"Courier New";mso-fareast-font-family:"Courier New"'><span
style='mso-list:Ignore'>o<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;
</span></span></span><![endif]>If you go to Wave 2 database, you’ll notice
there are no users set up.<o:p></o:p></span></p>

<p class=MsoListParagraph style='text-indent:-.25in;mso-list:l0 level1 lfo1'><span
style='mso-bookmark:_MailOriginal'><![if !supportLists]><span style='font-family:
Symbol;mso-fareast-font-family:Symbol;mso-bidi-font-family:Symbol'><span
style='mso-list:Ignore'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><![endif]>If the user’s wave is 1, they go immediately
into the Wave 1 database after logging in<o:p></o:p></span></p>

<p class=MsoListParagraph style='text-indent:-.25in;mso-list:l0 level1 lfo1'><span
style='mso-bookmark:_MailOriginal'><![if !supportLists]><span style='font-family:
Symbol;mso-fareast-font-family:Symbol;mso-bidi-font-family:Symbol'><span
style='mso-list:Ignore'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><![endif]>If the user’s wave is 2, they go immediately
into the Wave 2 database after logging in<o:p></o:p></span></p>

<p class=MsoListParagraph style='text-indent:-.25in;mso-list:l0 level1 lfo1'><span
style='mso-bookmark:_MailOriginal'><![if !supportLists]><span style='font-family:
Symbol;mso-fareast-font-family:Symbol;mso-bidi-font-family:Symbol'><span
style='mso-list:Ignore'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><![endif]>If the user’s wave is 0, they get prompted as to
which database they’d like to go into<o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'>All this will be in
effect at the next rollout this afternoon.<o:p></o:p></span></p>

<p class=MsoListParagraph><span style='mso-bookmark:_MailOriginal'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'><![if !vml]><img width=590 height=231
src="file:///C:/Users/dlounsbu/AppData/Local/Temp/msohtmlclip1/01/clip_image002.jpg"
v:shapes="Picture_x0020_2"><![endif]><o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-bookmark:_MailOriginal'><span
style='font-size:12.0pt;font-family:"Times New Roman",serif;mso-fareast-font-family:
"Times New Roman"'>This electronic message is intended to be for the use only
of the named recipient, and may contain information from the North Country
Initiative that is confidential or privileged. If you are not the intended
recipient, you are hereby notified that any disclosure, copying, distribution
or use of the contents of this message is strictly prohibited. If you have
received this message in error or are not the named recipient, please notify us
immediately, either by contacting the sender at the electronic mail address
noted above or by calling the North Country Initiative at (315) 755-2020 x 23,
and delete and destroy all copies of this message. </span></span><span
style='font-size:12.0pt;font-family:"Times New Roman",serif;mso-fareast-font-family:
"Times New Roman"'><o:p></o:p></span></p>


</body>

</html>

**Comment by dlounsbu** [comment]
Hi Jeff:

We set up a GitHub Issue to document this effort. 

Let's use this issue to keep up to date on this important matter.

**Comment by dlounsbu** [comment]
> 

I would like to propose that only you, Nick and I have full Admin access at this point. 

Other key users, like Jessica and Sandra, should have access to ALL COUNTIES, but they should not need ADMIN priv.

DL
