### ISSUE TITLE
Service Request by [Suffolk County] to adjust the date format in Milestones to be consistent   

### ISSUE THREAD

**Issue by donriepurcell** [dlounsbu/NYHEALing-IPAtracker-support#74]
- [ ] Qualtrics Service Request Form was received from User
- [ ] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by donriepurcell** [comment]
![Screen Shot 2021-12-15 at 11 27 15 PM](https://user-images.githubusercontent.com/80912517/146308389-7ccda4a0-9712-4055-b076-c709cf4f223b.png)

**Comment by donriepurcell** [comment]
Hi Jeff 
Please see in the example above (noted by the Putnam county coalition members) inconsistency in the **date format** in Milestones (specification).

**Comment by jbazinet1111** [comment]
Do you know if this record was just added and not yet saved to the database?

**Comment by donriepurcell** [comment]
I added the record and deleted it. 
They also did the same thing to illustrate the problem to me.
Really, I did not want to mess too much with their stuff.

**Comment by jbazinet1111** [comment]
Resolved.

**Comment by donriepurcell** [comment]
Hi Jeff
Thanks,...
