### ISSUE TITLE
Service Request by Anna Weiskopf - review user access 

### ISSUE THREAD

**Issue by dlounsbu** [dlounsbu/NYHEALing-IPAtracker-support#75]
- [x] Qualtrics Service Request Form was received from User
- [x] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by dlounsbu** [comment]
From: David Lounsbury 
Sent: Thursday, December 16, 2021 8:08 PM
To: aw3391@columbia.edu
Cc: Donrie Purcell <donrie.purcell@einsteinmed.edu>
Subject: IPA Tracker Maintence

Hi Anna:

We are reviewing users and access levels, and that may be the problem. Also, the designer is doing maintenance on the Tacker this evening, so that may be the issue, too.

First thing in the morning we will make sure you can log in!

Apologies for any inconvenience. 

DL

**Comment by dlounsbu** [comment]
@donriepurcell 

Please review for Anna in the morning! 

DL

**Comment by donriepurcell** [comment]
Hi Jeff 
I am trying to add Anna back to the IPA tracker and I keep getting the error below.
Please can you assist me with this. It is really important to the team that she is back in the system.

<img width="854" alt="Screen Shot 2021-12-17 at 8 46 21 AM" src="https://user-images.githubusercontent.com/80912517/146553812-5ea15ab2-28ac-4c37-8737-2271e6fff23b.png">

**Comment by donriepurcell** [comment]
Jeff 
Thank you. I resolve the problem myself.
