### ISSUE TITLE
Service Request by [Jessica Neufeld & Anna Weiskoff] to repair error messages received by Data Coordinators 

### ISSUE THREAD

**Issue by donriepurcell** [dlounsbu/NYHEALing-IPAtracker-support#77]
- [x] Qualtrics Service Request Form was received from User
- [x] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by donriepurcell** [comment]
Hi Jeff
A happy New Year to you, your family and loved ones. I wanted to bring to your attention that when in the tracker, moving back and forth between IPA monitoring and specification. The county data coordinators are experiencing consistent error messages. I have experienced the same issue. Hopefully we can resolve it soon.
![IPA Tracker Issue](https://user-images.githubusercontent.com/80912517/148417038-a28a9fbe-c3f6-4912-b11b-564e12f4f2cb.jpg)

**Comment by jbazinet1111** [comment]
Can you recreate this error on demand? If so, please send the steps. I cannot seem to trigger the error to appear.

**Comment by donriepurcell** [comment]
ok will do

**Comment by donriepurcell** [comment]
Hi Jeff,
Jessica also wrote the following:

"Multiple users are seeing an error message when logging onto the Tracker. The error message comes up as soon as they log in and not related to saving or entering information. The message looks like this: "Server Error in '/' Application. Cannot find table 0. Description: An unhandled exception occurred during the execution of the current web report. Please review the stack trace for more information about the error and where it originated in the code. Exception Details: System IndexOutOfRangeException: Cannot find table 0. "

**Comment by dlounsbu** [comment]
Interesting. I did not have this issue when I logged in. @donriepurcell, is there any pattern to who is seeing this issue? Can we follow up with a user with this issue? THANKS

**Comment by donriepurcell** [comment]
I did not have in this instance or this morning, but over the holiday period I did. I ignore it and went back and forth without problems.  
This morning I asked Anna what computer she is using and she indicated that she was using a pc not a mac.
I also tried entering into the tracker using Anna's password and I did not experience the problem.
Yet, it will irresponsible of me to ignore her and other county members frustrations.
I will reach out to Anna again in an email to see if she is still experiencing the problem.

**Comment by NBOVE1** [comment]
Thank you Donrie. I'm not able to replicate the issue either.

**Comment by donriepurcell** [comment]
Hi Jeff,
I was working on in the tracker I left it work on some graphs in and excel spreadsheet. I came back and was locked out. I tried entering and I got the error we tried replicating today. I appears to come and go intermittently.
![Screen Shot 2022-01-06 at 11 11 32 PM](https://user-images.githubusercontent.com/80912517/148490554-6eca0eba-c5f8-4a3c-b7d1-506eade5780a.png)

**Comment by donriepurcell** [comment]
I persisted, got into the tracker. Then tried to verify some data in Putnam county'S OEND strategy A5 and behold another error!
![Screen Shot 2022-01-06 at 11 23 41 PM](https://user-images.githubusercontent.com/80912517/148491518-5e44f53b-3edc-4f09-92d8-f6c348a27d79.png)


![Screen Shot 2022-01-06 at 11 22 10 PM](https://user-images.githubusercontent.com/80912517/148491306-8ed9adbc-fda0-40c7-8766-03b834169fcf.png)

**Comment by jbazinet1111** [comment]
I put some tracing in yesterday and it showed a possible solution to this intermittent error. I put that solution in place this morning. 

The second issue is my fault and is due to the Evaluation changes. Those are in place as well. Take a look when you can.

**Comment by donriepurcell** [comment]
Hi jeff 
Thanks

**Comment by donriepurcell** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40"><p class="MsoNormal" style="margin: 0in 0in 12pt; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><b><span style="font-size: 12pt; color: black;">From:<span class="Apple-converted-space"> </span></span></b><span style="font-size: 12pt; color: black;">Jessica Neufeld &lt;jn2434@columbia.edu&gt;<br><b>Date:<span class="Apple-converted-space"> </span></b>Monday, January 10, 2022 at 5:04 PM<br><b>To:<span class="Apple-converted-space"> </span></b>Donrie Purcell &lt;donrie.purcell@einsteinmed.edu&gt;<br><b>Cc:<span class="Apple-converted-space"> </span></b>David Lounsbury &lt;david.lounsbury@einsteinmed.edu&gt;<br><b>Subject:<span class="Apple-converted-space"> </span></b>Re: Errors codes in the IPA tracker<o:p></o:p></span></p>

CAUTION: This email comes from an external source; the attachments and/or links may compromise our secure environment. Do not open or click on suspicious emails. Please click on the “Phish Alert” button on the top right of the Outlook dashboard to report any suspicious emails.
--


<p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt; color: white;">Hi Donrie, <span class="Apple-converted-space"> </span></span><span style="font-size: 11pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;"><o:p> </o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;">Thank you for sharing that update. <o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;"><o:p> </o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;">I haven't heard about any issues so far regarding the tracker, however, I'll alert you if I do. <o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;"><o:p> </o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;">Best,<br>Jesica <o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;"><o:p> </o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;">On Mon, Jan 10, 2022 at 4:39 PM Donrie Purcell &lt;<a href="mailto:donrie.purcell@einsteinmed.edu" style="color: rgb(149, 79, 114); text-decoration: underline;">donrie.purcell@einsteinmed.edu</a>&gt; wrote:<o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;">Hi Jessica<span class="Apple-converted-space"> </span></span><span style="font-size: 11pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"> </span><span style="font-size: 11pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;">I have attempted to beta test the IPA tracker this today so as to verify whether or not the error codes we experienced last week persist.</span><span style="font-size: 11pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;">I was unable to replicate the error codes today, albeit several factors can affect whether or not they persist. For example, I am using my MacBook pro and not a PC. Also, in the past I’ve noticed that the problem comes and goes intermittently.<span class="Apple-converted-space"> </span></span><span style="font-size: 11pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"> </span><span style="font-size: 11pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><u><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;">If and when possible, can you liaise with your team to find out if they are still experiencing  these error codes and let me know.<span class="Apple-converted-space"> </span></span></u><span style="font-size: 11pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"> </span><span style="font-size: 11pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;">Jeff, David and I are working to make sure that you and your team have free and unfettered access to the tracker at all times.</span><span style="font-size: 11pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"> </span><span style="font-size: 11pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;">Thank you for all you do.</span><span style="font-size: 11pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"> </span><span style="font-size: 11pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; vertical-align: baseline;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif; color: black;"> </span><span style="font-size: 11pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; vertical-align: baseline;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif; color: black;">Regards<br>Donrie Purcell, PhD, MPH</span><span style="font-size: 11pt;"><o:p></o:p></span></p></html>
