### ISSUE TITLE
Service Request by [Donrie & David] to Cayuga County Rep.(Monika Salvage) to assign strategies in the IPA Tracker 

### ISSUE THREAD

**Issue by donriepurcell** [dlounsbu/NYHEALing-IPAtracker-support#78]
- [ ] Qualtrics Service Request Form was received from User
- [ ] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by donriepurcell** [comment]
From: Donrie Purcell <donrie.purcell@einsteinmed.edu>
Date: Monday, January 10, 2022 at 3:49 PM
To: msalvage@cayugacounty.us <msalvage@cayugacounty.us>
Cc: David Lounsbury <david.lounsbury@einsteinmed.edu>, Nasim Sabounchi <Nasim.Sabounchi@sph.cuny.edu>
Subject: Unassigned IPA Strategies 
Hi Monica
Allow me the opportunity to wish you and your family a wonderful 2022.
David and I were reviewing the data in the tracker and we noticed that some of the strategies  for Cayuga county was unassigned to a specific IPA.
 
Please see below:  
 
We would like to be of help in assigning these strategies to a particular IPA if need be, or remove them where necessary.
 
Please let us know if, where, or when we can be of help.
 
 
Regards
Donrie Purcell, PhD, MPH
 
Every generation has the obligation to free men's minds for a look at new worlds,....to look out from a higher plateau than the last generation.
Ellison S. Onizuka 


CONFIDENTIALITY: This email (including any attachments) may contain confidential, proprietary and/or privileged information. Any duplication, copying, distribution, dissemination, transmission, disclosure or use in any manner of this email (including any attachments) without the authorization of the sender is strictly prohibited. If you receive this email (including any attachments) in error, please notify the sender and delete this email (including any attachments) from your system. Thank you.

**Comment by dlounsbu** [comment]
Thanks Donrie! 

Please add projects and add label tags.

DL

**Comment by donriepurcell** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40"><p class="MsoNormal" style="margin: 0in 0in 12pt; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><b><span style="font-size: 12pt; color: black;">From:<span class="Apple-converted-space"> </span></span></b><span style="font-size: 12pt; color: black;">Donrie Purcell &lt;donrie.purcell@einsteinmed.edu&gt;<br><b>Date:<span class="Apple-converted-space"> </span></b>Tuesday, January 11, 2022 at 11:24 AM<br><b>To:<span class="Apple-converted-space"> </span></b>Anna N. Weiskopf &lt;aw3391@columbia.edu&gt;<br><b>Cc:<span class="Apple-converted-space"> </span></b>emr2241@columbia.edu &lt;emr2241@columbia.edu&gt;, David Lounsbury &lt;david.lounsbury@einsteinmed.edu&gt;<br><b>Subject:<span class="Apple-converted-space"> </span></b>Re: Unassigned IPA Strategies<o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;">Hi Anna,<u5:p></u5:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"><u5:p></u5:p>Please note that this was corrected in the system.<span class="Apple-converted-space"> </span><u5:p></u5:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"><u5:p> </u5:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"><span><img width="670" height="274" src="blob:https://github.com/d8cf96d8-5bf4-41dd-8715-d57d0965c1b0" alt="Table

Description automatically generated" v:shapes="Picture_x0020_1" style="height: 2.854in; width: 6.979in;"></span></span><span><u5:p></u5:p><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><u5:p><span> <o:p></o:p></span></u5:p></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; vertical-align: baseline;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif; color: black;">Regards<br>Donrie Purcell, PhD, MPH<u5:p></u5:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; vertical-align: baseline;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif; color: black;"><u5:p> </u5:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; vertical-align: baseline;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif; color: black;">Every generation has the obligation to free men's minds for a look at new worlds,....to look out from a higher plateau than the last generation.<br>Ellison S. Onizuka <br><br><br>CONFIDENTIALITY: This email (including any attachments) may contain confidential, proprietary and/or privileged information. Any duplication, copying, distribution, dissemination, transmission, disclosure or use in any manner of this email (including any attachments) without the authorization of the sender is strictly prohibited. If you receive this email (including any attachments) in error, please notify the sender and delete this email (including any attachments) from your system. Thank you.<u5:p></u5:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"><u5:p> </u5:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><u5:p><span> <o:p></o:p></span></u5:p></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"><u5:p> </u5:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in 0in 12pt; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><b><span style="font-size: 12pt; color: black;">From:<span class="Apple-converted-space"> </span></span></b><span style="font-size: 12pt; color: black;">Anna N. Weiskopf &lt;aw3391@columbia.edu&gt;<br><b>Date:<span class="Apple-converted-space"> </span></b>Tuesday, January 11, 2022 at 9:55 AM<br><b>To:<span class="Apple-converted-space"> </span></b>Emma Rodgers &lt;emr2241@columbia.edu&gt;<br><b>Cc:<span class="Apple-converted-space"> </span></b>Donrie Purcell &lt;donrie.purcell@einsteinmed.edu&gt;<br><b>Subject:<span class="Apple-converted-space"> </span></b>Re: FW: Unassigned IPA Strategies<u5:p></u5:p></span><span><o:p></o:p></span></p>

CAUTION: This email comes from an external source; the attachments and/or links may compromise our secure environment. Do not open or click on suspicious emails. Please click on the “Phish Alert” button on the top right of the Outlook dashboard to report any suspicious emails.
--


<p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt; color: white;">Hi Donrie,</span><span><u5:p></u5:p><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;"><u5:p> </u5:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;">These are Cayuga's safer prescribing IPAs. I tried going into the tracker to rename it, however, it won't save the change. When I tried renaming again, it shows the change but won't change the overall IPA name on the left side of the screen (see screenshot below). Can you see if you can change it?<u5:p></u5:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;"><u5:p> </u5:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;">Thanks,<u5:p></u5:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;">Anna<u5:p></u5:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;"><u5:p> </u5:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in 0in 12pt; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;"><span><img width="510" height="208" src="blob:https://github.com/da0ce415-6bba-4472-9245-eb9c0cf61ebf" v:shapes="Picture_x0020_2" style="height: 2.166in; width: 5.302in;"></span></span><span><u5:p></u5:p><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;"><u5:p> </u5:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;">On Tue, Jan 11, 2022 at 9:46 AM Emma Rodgers &lt;</span><span><a href="mailto:emr2241@columbia.edu" style="color: rgb(149, 79, 114); text-decoration: underline;"><span style="font-size: 11pt;">emr2241@columbia.edu</span></a></span><span style="font-size: 11pt;">&gt; wrote:<u5:p></u5:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;">Hi Donrie,<u5:p></u5:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;"><u5:p> </u5:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;">Anna - please add this to our agenda today.<u5:p></u5:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;"><u5:p> </u5:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;">Thanks,<u5:p></u5:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;">Emma<u5:p></u5:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;"><u5:p> </u5:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;"><u5:p> </u5:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 11pt;">On Tue, Jan 11, 2022 at 8:00 AM Donrie Purcell &lt;</span><span><a href="mailto:donrie.purcell@einsteinmed.edu" target="_blank" style="color: rgb(149, 79, 114); text-decoration: underline;"><span style="font-size: 11pt;">donrie.purcell@einsteinmed.edu</span></a></span><span style="font-size: 11pt;">&gt; wrote:<u5:p></u5:p></span><span><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;">Hi Emma<span class="Apple-converted-space"> </span></span><span><u5:p></u5:p><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"> </span><span><u5:p></u5:p><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;">I am forwarding this to you. I believe I sent this Nasim in error.</span><span><u5:p></u5:p><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"> </span><span><u5:p></u5:p><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; vertical-align: baseline;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif; color: black;">Regards<br>Donrie Purcell, PhD, MPH</span><span><u5:p></u5:p><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; vertical-align: baseline;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif; color: black;"> </span><span><u5:p></u5:p><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; vertical-align: baseline;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif; color: black;">Every generation has the obligation to free men's minds for a look at new worlds,....to look out from a higher plateau than the last generation.<br>Ellison S. Onizuka <br><br><br>CONFIDENTIALITY: This email (including any attachments) may contain confidential, proprietary and/or privileged information. Any duplication, copying, distribution, dissemination, transmission, disclosure or use in any manner of this email (including any attachments) without the authorization of the sender is strictly prohibited. If you receive this email (including any attachments) in error, please notify the sender and delete this email (including any attachments) from your system. Thank you.</span><span><u5:p></u5:p><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"> </span><span><u5:p></u5:p><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"> </span><span><u5:p></u5:p><o:p></o:p></span></p><p class="MsoNormal" style="margin: 0in; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif;"> </span><span><u5:p></u5:p><o:p></o:p></span></p></html>
