### ISSUE TITLE
Service Request by Anna Wieskopf about Strategy Feedback-QI updates and edits not saving

### ISSUE THREAD

**Issue by donriepurcell** [dlounsbu/NYHEALing-IPAtracker-support#8]
- [x] Qualtrics Service Request Form was received from User
- [x] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [x] Problem FULLY RESOLVED and Issue is Closed
- [x] Post-Service e-mail was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

It seems that there is a problem with saving ANY updated info in the SPECIFICATION Feedback QI element. I think this is a bug. 
I do not think it is related to renaming an existing IPA. 

3. Any additional context, such as screenshots about the problem.

**Comment by donriepurcell** [comment]
Hi Donrie,

It looks like every time I update the name of an IPA, it deletes all my information under the feedback/QI section. Do you know why that keeps happening?

Best,
Anna

-- 
Anna Weiskopf, MPA
Research Coordinator
Social Intervention Group, HEALing Communities Study
Columbia University School of Social Work
1255 Amsterdam Avenue, Suite 807
New York, NY 10027
Email: aw3391@columbia.edu
Cell: 212-853-7053 
Website: https://sig.columbia.edu/

**Comment by dlounsbu** [comment]
Thanks for setting up this Issue Card! Remember to 'assign' the Issue to our IPA Tracker Service Request 'Project', to that is gets triaged to the 'To do' column in the Project.

**Comment by dlounsbu** [comment]
Hi Donrie: 

It seems that there is a problem with saving ANY updated info in the SPECIFICATION Feedback QI element. 

I think this is a bug. 

I do not think it is related to renaming an existing IPA. 

Let me know what you learn. 
THANKS

**Comment by dlounsbu** [comment]
@donriepurcell : Any action from Jeff on this one today?

DL

**Comment by donriepurcell** [comment]
No nothing! 
I do believe Ana has a point on wanting to review one measure from a strategy at a time. 
I find it busy when there are so many strategies in any one IPA and a bit convoluted. 
I hope we can help the RC's with this!

**Comment by dlounsbu** [comment]
> No nothing!
> I do believe Ana has a point on wanting to review one measure from a strategy at a time.
> I find it busy when there are so many strategies in any one IPA and a bit convoluted.
> I hope we can help the RC's with this!

Exactly, we need to help them be more clear and concise in every aspect of SPECIFICTION. Typically, there should only be ONE measure per strategy. Of course, they can have more Measures, but are they really going to report (MONITOR) them all in a reliable way.

I agree, it is a training issue for the Coaches. With Cayuga, they drafted very detailed plans that really do not add value in terms of actual implementation. This is my opinion. 

Over time, they should be able to streamline their IPAs/Strategies/Measures.

**Comment by donriepurcell** [comment]
Bearing this mind:

Can we ask Jeff if he can help with sorting for people like Anna or the other RC's who are visual or spatial ?

**Comment by dlounsbu** [comment]
> Bearing this mind:
> 
> Can we ask Jeff if he can help with sorting for people like Anna or the other RC's who are visual or spatial in terms of how they review the the tracker?

Maybe, yes. But the sorting should be automatic. We do not need to turn the table displays into spreadsheets. 

We need to train people to be parsimonious and to use the download feature. The tool is designed mainly to help with data entry, editing.

**Comment by dlounsbu** [comment]
> Hi Donrie,
> 
> It looks like every time I update the name of an IPA, it deletes all my information under the feedback/QI section. Do you know why that keeps happening?
> 
> Best,
> Anna
> 
> --
> Anna Weiskopf, MPA
> Research Coordinator
> Social Intervention Group, HEALing Communities Study
> Columbia University School of Social Work
> 1255 Amsterdam Avenue, Suite 807
> New York, NY 10027
> Email: [aw3391@columbia.edu](mailto:aw3391@columbia.edu)
> Cell: 212-853-7053
> Website: https://sig.columbia.edu/

FYI, I just checked this (8/18/2021), and this bug still persists. When you edit a strategy in SPECIFICATION and edit information to the Feedback/QI element,  it is not saving.

**Comment by dlounsbu** [comment]
> > Hi Donrie,
> > It looks like every time I update the name of an IPA, it deletes all my information under the feedback/QI section. Do you know why that keeps happening?
> > Best,
> > Anna
> > --
> > Anna Weiskopf, MPA
> > Research Coordinator
> > Social Intervention Group, HEALing Communities Study
> > Columbia University School of Social Work
> > 1255 Amsterdam Avenue, Suite 807
> > New York, NY 10027
> > Email: [aw3391@columbia.edu](mailto:aw3391@columbia.edu)
> > Cell: 212-853-7053
> > Website: https://sig.columbia.edu/
> 
> FYI, I just checked this (8/18/2021), and this bug still persists. When you edit a strategy in SPECIFICATION and edit information to the Feedback/QI element, it is not saving.

@jbazinet1111   Please see what you make of this. There is some sort of challenge updating and saving text in Strategy Feedback/QI.

**Comment by dlounsbu** [comment]
From: david lounsbury 
Sent: Thursday, August 19, 2021 12:15 PM
To: 'Anna N. Weiskopf' <aw3391@columbia.edu>
Cc: Donrie Purcell <donrie.purcell@einsteinmed.org>; Nicholas Bove <nicholas.bove@einsteinmed.org>; Anika Buch <ambuch@princeton.edu>; Nasim Sabounchi <Nasim.Sabounchi@sph.cuny.edu>; Emma Rodgers <emr2241@columbia.edu>
Subject: RE: Questions about IPA tracker

HI Anna:

So, it appears that the issue of saving updates to Strategy Feedback/QI has been fixed. 

I did some testing myself this morning, and it worked. 

Try things at your end and report back. If the Issue remains, please complete a new Request Support form via https://github.com/dlounsbu/NYHEALing-IPAtracker-support

Best and thanks,
David
