### ISSUE TITLE
Service Request by [veronica Salvas] on her ability to edit within the IPA tracker 

### ISSUE THREAD

**Issue by donriepurcell** [dlounsbu/NYHEALing-IPAtracker-support#82]
- [x] Qualtrics Service Request Form was received from User
- [x] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by dlounsbu** [comment]
Hi Donrie:

How can I assist with this now? If you want to investigate together, let me know.

**Comment by dlounsbu** [comment]
Hi Donrie:

I just looked at what Veronica is trying to do: Edit a monitoring data point, I think. 

And I could add, edit or delete it. No problem on my end. 

Maybe it is a Browser issue? I recommend Google Chrome. 

Did you replicate her issue??

D

**Comment by donriepurcell** [comment]
I could have also. It may be that she does not have management status

**Comment by donriepurcell** [comment]
In the past she has had problems navigating her MacBook, Nick can attest to that fact.

**Comment by dlounsbu** [comment]
I think we can close this issue, too, right?
