### ISSUE TITLE
Service Request by [Donrie Purcell] for List Options download with Measures associated Specific EBPs

### ISSUE THREAD

**Issue by donriepurcell** [dlounsbu/NYHEALing-IPAtracker-support#84]
- [ ] Qualtrics Service Request Form was received from User
- [ ] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by donriepurcell** [comment]
Hi Jeff,

I am wondering if you made the list options download available with the measures associated with the EBPs so that David and I can review them to update the codebook?
Kind regards
Donrie

**Comment by jbazinet1111** [comment]
Yes. The functionality has been released.

**Comment by donriepurcell** [comment]
Hi jeff 
I download the following:

<img width="1263" alt="Screen Shot 2022-02-16 at 12 07 26 PM" src="https://user-images.githubusercontent.com/80912517/154318205-7e051893-2a94-43e2-8ddc-8dabb4eee8db.png">

**Comment by donriepurcell** [comment]
Please direct me in terms of where I may have gone wrong. Usually you can spot these things in an instant.

**Comment by jbazinet1111** [comment]
If you scroll down to the measures, the EBP value will be in one of the columns to the right.

**Comment by donriepurcell** [comment]
<img width="1608" alt="Screen Shot 2022-02-16 at 12 12 44 PM" src="https://user-images.githubusercontent.com/80912517/154319160-ff31733d-f01c-420e-8e91-30264128673f.png">

**Comment by donriepurcell** [comment]
This is the last of the measures

**Comment by jbazinet1111** [comment]
Yeah. None of the OTHER MEASURES have an EBP value. That's generally the problem with those measures. Take a look at Primary Measures or one of the others. That third column should have data.

**Comment by donriepurcell** [comment]
Ok Great, 
That clears it up for David and I because we cannot really change what is assigned to the primary, secondary, and structural measures without engaging Columbia. Thanks once more. David and I will proceed from here.
