### ISSUE TITLE
Service Request by [Mia Christopher] on repairing errors

### ISSUE THREAD

**Issue by donriepurcell** [dlounsbu/NYHEALing-IPAtracker-support#85]
- [ ] Qualtrics Service Request Form was received from User
- [ ] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by donriepurcell** [comment]
[From: ]()David Lounsbury <noreply@qemailserver.com>
Date: Wednesday, March 9, 2022 at 1:33 PM
To: Donrie Purcell <donrie.purcell@einsteinmed.edu>
Subject: IPA Tracker Support Request Form Submitted
IPA SERVICE REQUEST SUMMARY


1. CONTACT INFORMATION:

Mia  Christopher

Email:  mm5651@columbia.edu

Phone:  2078121440


2. COUNTY

Erie


3. WHICH FEATURE(S):

Some other feature


4. BRIEF PROBLEM DESCRIPTION:

1. Can we please assign the unassigned IPAs to MOUD. I tried to rename it and it did not work. 2. When attempting to delete ONE strategy called 2B.1 curbside care (there were two), they both deleted. This also happened to the program manager. Is there a way to get this back?


5. URGENCY:

100


6. ANYTHING ELSE TO SHARE:

**Comment by donriepurcell** [comment]
I have edited and re-assigned the error by Mia. 
The next step is to look in my previous download for the data she lost and  give it to her to be re-entered.

**Comment by donriepurcell** [comment]
From: Donrie Purcell <donrie.purcell@einsteinmed.edu>
Date: Wednesday, March 9, 2022 at 2:54 PM
To: mm5651@columbia.edu <mm5651@columbia.edu>
Subject: Re: Data required !!
Hi Mia 
 
Please find attached all the data you will need to repopulate the fields lost for 2B1 Curbside.
 
Regards
Donrie Purcell, PhD, MPH
 
Every generation has the obligation to free men's minds for a look at new worlds,....to look out from a higher plateau than the last generation.
Ellison S. Onizuka 


CONFIDENTIALITY: This email (including any attachments) may contain confidential, proprietary and/or privileged information. Any duplication, copying, distribution, dissemination, transmission, disclosure or use in any manner of this email (including any attachments) without the authorization of the sender is strictly prohibited. If you receive this email (including any attachments) in error, please notify the sender and delete this email (including any attachments) from your system. Thank you.
 
 
[DUI_2022-02-24 Mia Christopher.xlsx](https://github.com/dlounsbu/NYHEALing-IPAtracker-support/files/8217730/DUI_2022-02-24.Mia.Christopher.xlsx)

**Comment by dlounsbu** [comment]
Hi Donrie:

This issue is fixed, right?

DL

**Comment by donriepurcell** [comment]
Yes sir 
I closed it yesterday
