### ISSUE TITLE
Service Request by [Add user ]Troubleshooting

### ISSUE THREAD

**Issue by donriepurcell** [dlounsbu/NYHEALing-IPAtracker-support#87]
- [ ] Qualtrics Service Request Form was received from User
- [ ] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by donriepurcell** [comment]
Hi @jbazinet1111 

I am having a bit of trouble adding a user or users to the tracker today. I am wondering if has anything to do with the MacBook as I do recall you mentioning something of the sort a while back.
I also tried adding someone via a PC which yielded the same result. Any guidance you can provide will be great as I know the folks at Columbia are awaiting a response from us.
Thank you so much
Donrie

**Comment by jbazinet1111** [comment]
Without an error message it is a little tough. Seldom is the issue a result of a Mac vs a PC. In this case, I came across a situation where my user did not get added and it was because the Wave field was not filled in. Perhaps this is the case with you?
If so, we can consider putting a message in place that will notify the user if the fields are not completed in full.

**Comment by donriepurcell** [comment]
Hi Jeff,
David came back in and was able to assist me.
Thank you. It seems that I have to add a couple digits to the password and ensure that the username is added to the user management list before proceeding.
Thanks for all you do
Regards 
Donrie
