### ISSUE TITLE
Service Request by [editing of demographics] on behalf of the Columbia team

### ISSUE THREAD

**Issue by donriepurcell** [dlounsbu/NYHEALing-IPAtracker-support#88]
- [x] Qualtrics Service Request Form was received from User
- [ ] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by dlounsbu** [comment]
From: David Lounsbury [mailto:noreply@qemailserver.com] 
Sent: Monday, March 14, 2022 1:52 PM
To: David Lounsbury <david.lounsbury@einsteinmed.edu>
Subject: IPA Tracker Support Request Form Submitted

IPA SERVICE REQUEST SUMMARY


1. CONTACT INFORMATION:

Jessica  Neufeld

Email:  [jn2434@columbia.edu](mailto:jn2434@columbia.edu)

Phone:  9175025218


2. COUNTY

All counties


3. WHICH FEATURE(S):

MONITORING: Creating, updated or deleting information about an implemented SMART Strategy, REPORTING: Downloading data to create a table, figure or other summary report


4. BRIEF PROBLEM DESCRIPTION:

An edit needs to be made to the demographics section. "F)Pacific Islander or Native Amer " should be changed to "Native Hawaiian or Other Pacific Islander"


5. URGENCY:

50


6. ANYTHING ELSE TO SHARE:

**Comment by dlounsbu** [comment]
Hi Donrie: 

Thanks for setting up this issue card. 

This request is easy, I think. Can you make this edit in LIST OPTIONS for Jessica?!

Best, D

**Comment by donriepurcell** [comment]
Hi profe
I am working on this as we speak,
I got some error codes that I took screen shots of.
However, before I send that stuff to Jeff I want to be sure it is properly vetted. I am updating my computer because I noticed some funny stuff today to make sure that’s not part of the problem.
I’m upstairs, call me if need be.

Sent from my iPhone

On Mar 14, 2022, at 4:14 PM, David W Lounsbury ***@***.***> wrote:

﻿
CAUTION: This email comes from an external source; the attachments and/or links may compromise our secure environment. Do not open or click on suspicious emails. Please click on the “Phish Alert” button on the top right of the Outlook dashboard to report any suspicious emails.

Hi Donrie:

Thanks for setting up this issue card.

This request is easy, I think. Can you make this edit in LIST OPTIONS for Jessica?!

Best, D

—
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdlounsbu%2FNYHEALing-IPAtracker-support%2Fissues%2F88%23issuecomment-1067243717&data=04%7C01%7Cdonrie.purcell%40einsteinmed.edu%7C67135ef2eaa84895596308da05f74ca1%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637828856981677242%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Uob93B8aN4OayJXfMsAEmSoT%2BsfCvVllTrwb%2BwdJwxg%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATJKBBMTFEXLUCUZXVVMCW3U76M3ZANCNFSM5QWSQWWQ&data=04%7C01%7Cdonrie.purcell%40einsteinmed.edu%7C67135ef2eaa84895596308da05f74ca1%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637828856981677242%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BIB5W6SCM%2FCpuGhjnBuLcTdatyQ%2FZolfAOb3FgIL8DA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cdonrie.purcell%40einsteinmed.edu%7C67135ef2eaa84895596308da05f74ca1%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637828856981677242%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0M8VQW%2BcPRVAZJMuupw11xgFSuG9Q8mGtEaV4Il3RbA%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cdonrie.purcell%40einsteinmed.edu%7C67135ef2eaa84895596308da05f74ca1%7C9c01f0fd65e040c089a82dfd51e62025%7C0%7C0%7C637828856981677242%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2B02Ot3LCuMN%2FeltpuVwp4Mwr5BV1qBVCh5wsmmrMlrc%3D&reserved=0>.

**Comment by dlounsbu** [comment]
Hi Donrie:

Ok. Let me know if you need me to work on this for JN.

DL

**Comment by donriepurcell** [comment]
Hi David 
The demographic change was completed since Monday and you were cc'd on the email. All that remains is for Jeff to do his part in terms of allowing edits to other strategies
