### ISSUE TITLE
Service Request by Sandra Rodriguez - Reconciliation of the ORCCAT Report with July 2021 with the IPA Tracker

### ISSUE THREAD

**Issue by donriepurcell** [dlounsbu/NYHEALing-IPAtracker-support#9]
- [x] Qualtrics Service Request Form was received from User
- [x] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [ ] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by donriepurcell** [comment]
1. Reconciliation of the ORCCAT for Cayuga County with the IPA tracker to find Discrepancies or symmetry in the datat.
2. Contact Nasim (County Coach) to establish and relay communications to Monica and the county RC
3. Sandra Rodriquez will be cc'd and directly emailed on all findings and contact

**Comment by dlounsbu** [comment]
Donrie and Mahdi: 

Please provide an update on the Cayuga ORCCAT Data Harmonization efforts.

If you have any questions or if you are stuck, please post comments here, to this Issue card, so all of us can weigh in and problem solve with you.

Thank you!

**Comment by NBOVE1** [comment]
Hi All,
Yes, please let me know how I can support. I'm available to jump on a call today and problem solve around any challenges faced.
Much appreciated,
Nick

**Comment by dlounsbu** [comment]
> Hi All,
> Yes, please let me know how I can support. I'm available to jump on a call today and problem solve around any challenges faced.
> Much appreciated,
> Nick

Thanks Nock!

@donriepurcell any updates on this Issue?!

**Comment by donriepurcell** [comment]
Hi Nick,
I apologize about not getting back to you earlier. I was looking at different approaches to do this quickly. The tedious line by line option is best for now. A soon as I can provide a comprehensive strategy on the columns of interest from the downloads that will get us to where we need to be I will certainly let you know. This way you won't have to be sifting through the sand unnecessarily.

**Comment by dlounsbu** [comment]
Here is a copy of the completed ORCCAT Coding Assessment that Donrie and I have been working on. 
[3_Cayuga_ORCCAT_July 2021 Comparison file v3 DL DP.xlsx](https://github.com/dlounsbu/NYHEALing-IPAtracker-support/files/7079850/3_Cayuga_ORCCAT_July.2021.Comparison.file.v3.DL.DP.xlsx)


From HCS Protocol (updated as 2021-01-01) Section IV – Links to Most Up-to-date ORCCA Materials
This is the link to the ORCCA section of the RTI portal: https://healingcommunities.rti.org/WorkGroups/ORCCA. 

This includes a folder containing the ORCCA Menus, which list strategies form implementing the three required EBPs and a folder for ORCCA “Technical Assistance Guides (TAGs)” for the strategies outlined in the menus as well as accessing priority populations.

**Comment by dlounsbu** [comment]
Per meeting with Sandra and Jessica yesterday (8/31), we learned that they are cleaning up the IPAs/Strategies for all the counties. We also learned that she does not report summary metrics to NIDA for ORCCAT, but instead a line of descriptive information for each STRATEGY x (SECTOR | VENUE). For example, if STRATEGY A impacts HEALTHCARE and BEHAVIORAL and CRIMINAL JUSTICE sectors, in 2 VENUES, and STRATEGY B impacts HEALTHCARE only in 1 venue, then we would have 6 rows, I believe.

**Comment by dlounsbu** [comment]
david lounsbury 
Sent: Wednesday, September 8, 2021 11:18 AM
To: Sandra Rodriguez <sr3717@columbia.edu>; Nicholas Bove <nicholas.bove@einsteinmed.org>
Cc: Donrie Purcell <donrie.purcell@einsteinmed.org>
Subject: RE: access to IPA tracker

Hi Sandra:

Thanks great! 

Regarding the matter of discontinued IPAs, we should develop guidance on this. 

One option is to update or add a Milestone that indicates that a particular Smart Strategy has been terminated/decommissioned. That would give us an effective date stamp for that event. 

A strategy can be deleted from the Tracker, too, but it would no longer be visible in the Tracker, and any associated data for that strategy would not be visible, either. 

There may be other ways to filter out discontinued IPAs. We are open to your suggestions. 

Best,
David



From: Sandra Rodriguez [mailto:sr3717@columbia.edu] 
Sent: Wednesday, September 8, 2021 11:09 AM
To: Nicholas Bove <nicholas.bove@einsteinmed.org>; david lounsbury <david.lounsbury@einsteinmed.org>
Cc: Donrie Purcell <donrie.purcell@einsteinmed.org>
Subject: Re: access to IPA tracker

CAUTION: This email comes from an external source; the attachments and/or links may compromise our secure environment. Do not open or click on suspicious emails. Please click on the “Phish Alert” button on the top right of the Outlook dashboard to report any suspicious emails.
Good Morning Everyone 

Just wanted to let you all know that I went into the IPA Tracker and was able to pull out information for updating the ORCCA Tracker for the month of August. So far so good. My only question or issue is regarding dates, but that can be an email to the county staff. I do have one question. Does the IPA Tracker have a place for discontinued IPAs?  

Sandra

**Comment by dlounsbu** [comment]
@NBOVE1 At your convenience, please reach out to Sandra to see if she needs and data pulls, tables, etc, for her ORCCAT reporting. THANKS

**Comment by NBOVE1** [comment]
@dlounsbu  Sure, I'll reach out today.

**Comment by NBOVE1** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/NBOVE/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/NBOVE/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/NBOVE/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link=blue vlink="#954F72" style='tab-interval:.5in'>


<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
color:#1F497D'>Thanks for the update Sandra. David and Donrie plan to touch
base during coaching calls to reinforce the need to update the IPA Tracker as
often as possible.<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
color:#1F497D'>Best,<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
color:#1F497D'>Nick<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;
color:#1F497D'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal style='mso-outline-level:1'><b><span style='font-size:11.0pt;
font-family:"Calibri",sans-serif'>From:</span></b><span style='font-size:11.0pt;
font-family:"Calibri",sans-serif'> Sandra Rodriguez [<a
href="mailto:sr3717@columbia.edu">mailto:sr3717@columbia.edu</a>] <br>
<b>Sent:</b> Wednesday, September 29, 2021 12:22 PM<br>
<b>To:</b> Nicholas Bove &lt;<a href="mailto:nicholas.bove@einsteinmed.org">nicholas.bove@einsteinmed.org</a>&gt;<br>
<b>Subject:</b> Re: ORCCAT Reporting<o:p></o:p></span></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>



CAUTION: This email comes from an external source; the   attachments and/or links may compromise our secure environment. Do not open   or click on suspicious emails. Please click on the “Phish Alert” button on   the top right of the Outlook dashboard to report any suspicious emails.
--




<p class=MsoNormal>Hi Nick <o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>Yes, I have been able to pull data from the IPA tracker for
the ORCCAT. I think the bigger issue is making sure the information goes into
the IPA Tracker as well as changes made to the IPA. <o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>Sandra<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>On Wed, Sep 29, 2021 at 11:59 AM Nicholas Bove &lt;<a
href="mailto:nicholas.bove@einsteinmed.org">nicholas.bove@einsteinmed.org</a>&gt;
wrote:<o:p></o:p></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'>Hi
Sandra,<o:p></o:p></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'>I
hope your week’s going well! I wanted to follow up regarding pulling ORCCAT
reports from the tracker. Have you been successful with pulling data needed? Do
you need any further support?<o:p></o:p></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'>Much
appreciated,<o:p></o:p></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'>Nick<o:p></o:p></p>


</body>

</html>
